// VOCA multi-language course curriculum
// Category metadata is shared; words are per target-language.
import { BULK_ZH, BULK_EN } from '@/lib/coursesBulk';

export const LANGS = [
  { code: 'zh', name: 'Хятад',    native: '中文',     flag: '🇨🇳', sttLang: 'zh-CN' },
  { code: 'en', name: 'Англи',    native: 'English',  flag: '🇬🇧', sttLang: 'en-US' },
  { code: 'ja', name: 'Япон',     native: '日本語',   flag: '🇯🇵', sttLang: 'ja-JP', soon: true },
  { code: 'ko', name: 'Солонгос', native: '한국어',   flag: '🇰🇷', sttLang: 'ko-KR', soon: true },
];

export const CATEGORY_META = [
  { id: 'greetings',     num: 1,  name: 'Мэндчилгээ',       emoji: '👋', color: '#F59E0B', desc: 'Танилцах, мэндлэх, баяртай гэх өдөр тутмын мэндчилгээ.' },
  { id: 'introductions', num: 2,  name: 'Танилцах',          emoji: '🧑‍🤝‍🧑', color: '#3B82F6', desc: 'Өөрийгөө танилцуулах, нэр, нас, гарал үүсэл.' },
  { id: 'family',        num: 3,  name: 'Гэр бүл',           emoji: '👨‍👩‍👧', color: '#10B981', desc: 'Гэр бүлийн гишүүд, садан төрөл.' },
  { id: 'home',          num: 4,  name: 'Гэр',               emoji: '🏠', color: '#FB923C', desc: 'Гэр орон, тавилга, өрөөнүүд.' },
  { id: 'food',          num: 5,  name: 'Хоол',              emoji: '🍜', color: '#FACC15', desc: 'Хоол хүнс, ундаа, ресторан.' },
  { id: 'shopping',      num: 6,  name: 'Худалдаа',          emoji: '🛒', color: '#EC4899', desc: 'Дэлгүүр хэсэх, үнэ асуух, төлбөр.' },
  { id: 'payment',       num: 7,  name: 'Төлбөр, мөнгө',     emoji: '💳', color: '#14B8A6', desc: 'Мөнгө, төлбөр, банк.' },
  { id: 'transport',     num: 8,  name: 'Нийтийн тээвэр',    emoji: '🚌', color: '#0EA5E9', desc: 'Унаа, тээвэр, зам.' },
  { id: 'taxi',          num: 9,  name: 'Такси',             emoji: '🚕', color: '#F59E0B', desc: 'Такси дуудах, чиглэл хэлэх.' },
  { id: 'directions',    num: 10, name: 'Зам асуух',         emoji: '🗺️', color: '#FBBF24', desc: 'Чиглэл, байршил асуух.' },
  { id: 'hospital',      num: 11, name: 'Эмнэлэг',           emoji: '🏥', color: '#EF4444', desc: 'Эрүүл мэнд, эмнэлэг.' },
  { id: 'pharmacy',      num: 12, name: 'Эмийн сан',         emoji: '💊', color: '#06B6D4', desc: 'Эмийн сан, эм тан.' },
  { id: 'work',          num: 13, name: 'Ажил',              emoji: '💼', color: '#8B5CF6', desc: 'Ажил мэргэжил, ажлын байр.' },
  { id: 'school',        num: 14, name: 'Сургууль',          emoji: '🎓', color: '#7C3AED', desc: 'Сургууль, хичээл, суралцах.' },
  { id: 'technology',    num: 15, name: 'Технологи',         emoji: '📱', color: '#FBBF24', desc: 'Утас, компьютер, интернэт.' },
  { id: 'clothes',       num: 16, name: 'Хувцас',            emoji: '👕', color: '#EC4899', desc: 'Хувцас, өмсгөл.' },
  { id: 'weather',       num: 17, name: 'Цаг агаар',         emoji: '🌤️', color: '#38BDF8', desc: 'Цаг агаар, улирал.' },
  { id: 'freetime',      num: 18, name: 'Чөлөөт цаг',        emoji: '🏀', color: '#22C55E', desc: 'Хобби, спорт, амралт.' },
  { id: 'travel',        num: 19, name: 'Аялал',             emoji: '✈️', color: '#60A5FA', desc: 'Аялал, онгоц, зочид буудал.' },
  { id: 'emergency',     num: 20, name: 'Яаралтай нөхцөл',   emoji: '🚨', color: '#EF4444', desc: 'Яаралтай, аюултай нөхцөл.' },
  { id: 'irregular-verbs', num: 21, name: 'Дүрмийн бус үйл үг', emoji: '🔄', color: '#6366F1', desc: 'Англи хэлний өнгөрсөн ба өнгөрсөн үйл үгийн дүрмийн бус хувирал.' },
];

// word helper: target, reading, mn, type, examples[[target,mn]], extra{syn,ant,rel,mn(mnemonic),emoji,past,pastParticiple}
function w(target, reading, mn, type, examples = [], extra = {}) {
  const id = extra.id || (reading || target).toLowerCase().replace(/[^a-z0-9]+/g, '-') || encodeURIComponent(target);
  return {
    id,
    target, reading, mn, type,
    word: target, ipa: reading, // aliases for UI compatibility
    examples: examples.map(([t, m]) => ({ en: t, mn: m })),
    synonyms: extra.syn || [], antonyms: extra.ant || [], related: extra.rel || [],
    mnemonic: extra.mn || '', emoji: extra.emoji || '',
    pastSimple: extra.past || '', pastParticiple: extra.pastParticiple || '',
  };
}

// ── ENGLISH ──
const EN = {
  greetings: [
    w('hello', 'həˈloʊ', 'сайн уу', 'Interjection', [['Hello, how are you?', 'Сайн уу, юу байна?']], { syn: ['hi'], ant: ['goodbye'], rel: ['hi', 'welcome'], emoji: '👋' }),
    w('goodbye', 'ɡʊdˈbaɪ', 'баяртай', 'Interjection', [['Goodbye, see you tomorrow.', 'Баяртай, маргааш уулзъя.']], { syn: ['bye'], ant: ['hello'], emoji: '👋' }),
    w('thanks', 'θæŋks', 'баярлалаа', 'Interjection', [['Thanks for your help.', 'Тусалсанд баярлалаа.']], { emoji: '🙏' }),
    w('please', 'pliːz', 'гуйя', 'Adverb', [['Please sit down.', 'Сууна уу.']], { emoji: '🙏' }),
    w('sorry', 'ˈsɒri', 'уучлаарай', 'Interjection', [['Sorry, I am late.', 'Уучлаарай, хоцорлоо.']], { emoji: '😔' }),
    w('welcome', 'ˈwelkəm', 'тавтай морил', 'Interjection', [['Welcome to Mongolia!', 'Монголд тавтай морил!']], { emoji: '🎉' }),
    w('good morning', 'ɡʊd ˈmɔːnɪŋ', 'өглөөний мэнд', 'Phrase', [['Good morning, teacher!', 'Өглөөний мэнд, багш аа!']], { emoji: '🌅' }),
    w('good night', 'ɡʊd naɪt', 'сайхан амраарай', 'Phrase', [['Good night!', 'Сайхан амраарай!']], { emoji: '🌙' }),
    w('excuse me', 'ɪkˈskjuːz miː', 'уучлаарай (анхаарал)', 'Phrase', [['Excuse me, where is the bank?', 'Уучлаарай, банк хаана байна?']], { emoji: '🙋' }),
  ],
  introductions: [
    w('name', 'neɪm', 'нэр', 'Noun', [['My name is Bat.', 'Миний нэр Бат.']], { emoji: '📛' }),
    w('age', 'eɪdʒ', 'нас', 'Noun', [['What is your age?', 'Та хэдэн настай вэ?']], { emoji: '🎂' }),
    w('friend', 'frend', 'найз', 'Noun', [['He is my friend.', 'Тэр миний найз.']], { emoji: '🤝' }),
    w('meet', 'miːt', 'уулзах', 'Verb', [['Nice to meet you.', 'Танилцсандаа баяртай.']], { emoji: '👋' }),
  ],
  family: [
    w('mother', 'ˈmʌðər', 'ээж', 'Noun', [['My mother is a teacher.', 'Миний ээж багш.']], { syn: ['mom'], ant: ['father'], emoji: '👩' }),
    w('father', 'ˈfɑːðər', 'аав', 'Noun', [['His father works hard.', 'Түүний аав шаргуу ажилладаг.']], { ant: ['mother'], emoji: '👨' }),
    w('sister', 'ˈsɪstər', 'эгч/дүү', 'Noun', [['I have one sister.', 'Надад нэг эгчтэй.']], { ant: ['brother'], emoji: '👧' }),
    w('brother', 'ˈbrʌðər', 'ах/дүү', 'Noun', [['My brother is tall.', 'Миний ах өндөр.']], { ant: ['sister'], emoji: '👦' }),
  ],
  home: [
    w('house', 'haʊs', 'байшин', 'Noun', [['This is a big house.', 'Энэ том байшин.']], { emoji: '🏠' }),
    w('room', 'ruːm', 'өрөө', 'Noun', [['My room is clean.', 'Миний өрөө цэвэрхэн.']], { emoji: '🚪' }),
    w('door', 'dɔːr', 'хаалга', 'Noun', [['Open the door.', 'Хаалгаа онгойлго.']], { emoji: '🚪' }),
    w('table', 'ˈteɪbl', 'ширээ', 'Noun', [['The book is on the table.', 'Ном ширээн дээр.']], { emoji: '🪑' }),
  ],
  food: [
    w('food', 'fuːd', 'хоол', 'Noun', [['The food is delicious.', 'Хоол амттай.']], { emoji: '🍲' }),
    w('water', 'ˈwɔːtər', 'ус', 'Noun', [['I drink water.', 'Би ус уудаг.']], { emoji: '💧' }),
    w('eat', 'iːt', 'идэх', 'Verb', [['Let us eat.', 'Хооллоё.']], { emoji: '🍽️' }),
    w('tea', 'tiː', 'цай', 'Noun', [['She likes tea.', 'Тэр цайнд дуртай.']], { emoji: '🍵' }),
    w('coffee', 'ˈkɒfi', 'кофе', 'Noun', [['One coffee, please.', 'Нэг кофе авъя.']], { emoji: '☕' }),
  ],
  shopping: [
    w('price', 'praɪs', 'үнэ', 'Noun', [['What is the price of this?', 'Энэ ямар үнэтэй вэ?'], ['The price is too high.', 'Үнэ хэт өндөр байна.']], { syn: ['cost', 'value'], ant: ['discount'], rel: ['expensive', 'cheap', 'buy'], mn: 'PRICE = Pay + Amount → Үнэ', emoji: '🏷️' }),
    w('expensive', 'ɪkˈspensɪv', 'үнэтэй', 'Adjective', [['This bag is expensive.', 'Энэ цүнх үнэтэй.']], { ant: ['cheap'], rel: ['price'], emoji: '💵' }),
    w('cheap', 'tʃiːp', 'хямд', 'Adjective', [['This shirt is cheap.', 'Энэ цамц хямд.']], { ant: ['expensive'], emoji: '👛' }),
    w('buy', 'baɪ', 'худалдан авах', 'Verb', [['I want to buy this.', 'Би үүнийг авмаар байна.']], { ant: ['sell'], emoji: '🛍️' }),
    w('sell', 'sel', 'зарах', 'Verb', [['They sell electronics.', 'Тэд цахилгаан бараа зардаг.']], { ant: ['buy'], emoji: '🎁' }),
    w('discount', 'ˈdɪskaʊnt', 'хямдрал', 'Noun', [['There is a 20% discount.', '20% хямдралтай.']], { emoji: '🏷️' }),
    w('size', 'saɪz', 'хэмжээ', 'Noun', [['What size do you wear?', 'Та ямар хэмжээ өмсдөг вэ?']], { emoji: '📏' }),
    w('color', 'ˈkʌlər', 'өнгө', 'Noun', [['I like this color.', 'Би энэ өнгөнд дуртай.']], { emoji: '🎨' }),
    w('receipt', 'rɪˈsiːt', 'баримт', 'Noun', [['Can I have the receipt?', 'Та надад баримт өгөх үү?']], { emoji: '🧾' }),
    w('try on', 'traɪ ɒn', 'өмсөж үзэх', 'Verb', [['Can I try this on?', 'Би үүнийг өмсөж үзэж болох уу?']], { emoji: '👕' }),
  ],
  payment: [
    w('money', 'ˈmʌni', 'мөнгө', 'Noun', [['I have no money.', 'Надад мөнгө байхгүй.']], { emoji: '💰' }),
    w('pay', 'peɪ', 'төлөх', 'Verb', [['How can I pay?', 'Би яаж төлөх вэ?']], { emoji: '💳' }),
    w('cash', 'kæʃ', 'бэлэн мөнгө', 'Noun', [['Do you accept cash?', 'Бэлэн мөнгө авах уу?']], { ant: ['card'], emoji: '💵' }),
    w('card', 'kɑːrd', 'карт', 'Noun', [['I will pay by card.', 'Картаар төлнө.']], { emoji: '💳' }),
  ],
  transport: [
    w('bus', 'bʌs', 'автобус', 'Noun', [['The bus is late.', 'Автобус хоцорч байна.']], { emoji: '🚌' }),
    w('train', 'treɪn', 'галт тэрэг', 'Noun', [['The train is fast.', 'Галт тэрэг хурдан.']], { emoji: '🚆' }),
    w('ticket', 'ˈtɪkɪt', 'тасалбар', 'Noun', [['I need two tickets.', 'Хоёр тасалбар хэрэгтэй.']], { emoji: '🎫' }),
  ],
  taxi: [
    w('taxi', 'ˈtæksi', 'такси', 'Noun', [['Call a taxi, please.', 'Такси дуудаач.']], { emoji: '🚕' }),
    w('driver', 'ˈdraɪvər', 'жолооч', 'Noun', [['The driver is kind.', 'Жолооч эелдэг.']], { emoji: '🧑‍✈️' }),
    w('stop', 'stɒp', 'зогсох', 'Verb', [['Please stop here.', 'Энд зогсооно уу.']], { emoji: '🛑' }),
  ],
  directions: [
    w('left', 'left', 'зүүн', 'Noun', [['Turn left here.', 'Энд зүүн эргэ.']], { ant: ['right'], emoji: '⬅️' }),
    w('right', 'raɪt', 'баруун', 'Noun', [['Go to the right.', 'Баруун тийш яв.']], { ant: ['left'], emoji: '➡️' }),
    w('straight', 'streɪt', 'чигээрээ', 'Adverb', [['Go straight ahead.', 'Чигээрээ яв.']], { emoji: '⬆️' }),
  ],
  hospital: [
    w('doctor', 'ˈdɒktər', 'эмч', 'Noun', [['I need a doctor.', 'Надад эмч хэрэгтэй.']], { emoji: '🧑‍⚕️' }),
    w('medicine', 'ˈmedɪsɪn', 'эм', 'Noun', [['Take this medicine.', 'Энэ эмийг уу.']], { emoji: '💊' }),
    w('sick', 'sɪk', 'өвчтэй', 'Adjective', [['I feel sick.', 'Би өвчтэй байна.']], { emoji: '🤒' }),
  ],
  pharmacy: [
    w('pill', 'pɪl', 'шахмал', 'Noun', [['Take one pill a day.', 'Өдөрт нэг шахмал уу.']], { emoji: '💊' }),
    w('fever', 'ˈfiːvər', 'халуурах', 'Noun', [['I have a fever.', 'Би халуурч байна.']], { emoji: '🌡️' }),
  ],
  work: [
    w('work', 'wɜːrk', 'ажил', 'Noun', [['I go to work at 9.', '9 цагт ажилдаа очдог.']], { syn: ['job'], emoji: '💼' }),
    w('office', 'ˈɒfɪs', 'оффис', 'Noun', [['The office is downtown.', 'Оффис хотын төвд.']], { emoji: '🏢' }),
    w('meeting', 'ˈmiːtɪŋ', 'хурал', 'Noun', [['We have a meeting.', 'Бид хуралтай.']], { emoji: '📅' }),
  ],
  school: [
    w('school', 'skuːl', 'сургууль', 'Noun', [['I study at school.', 'Би сургуульд сурдаг.']], { emoji: '🏫' }),
    w('teacher', 'ˈtiːtʃər', 'багш', 'Noun', [['Our teacher is kind.', 'Манай багш эелдэг.']], { ant: ['student'], emoji: '🧑‍🏫' }),
    w('student', 'ˈstuːdnt', 'оюутан', 'Noun', [['He is a good student.', 'Тэр сайн оюутан.']], { ant: ['teacher'], emoji: '🧑‍🎓' }),
    w('learn', 'lɜːrn', 'сурах', 'Verb', [['I want to learn.', 'Би сурмаар байна.']], { emoji: '🧠' }),
  ],
  technology: [
    w('phone', 'foʊn', 'утас', 'Noun', [['My phone is new.', 'Миний утас шинэ.']], { emoji: '📱' }),
    w('computer', 'kəmˈpjuːtər', 'компьютер', 'Noun', [['I work on a computer.', 'Компьютер дээр ажилладаг.']], { emoji: '💻' }),
    w('internet', 'ˈɪntərnet', 'интернэт', 'Noun', [['The internet is slow.', 'Интернэт удаан.']], { emoji: '🌐' }),
  ],
  clothes: [
    w('shirt', 'ʃɜːrt', 'цамц', 'Noun', [['This shirt is blue.', 'Энэ цамц цэнхэр.']], { emoji: '👕' }),
    w('shoes', 'ʃuːz', 'гутал', 'Noun', [['My shoes are new.', 'Миний гутал шинэ.']], { emoji: '👟' }),
    w('hat', 'hæt', 'малгай', 'Noun', [['He wears a hat.', 'Тэр малгай өмссөн.']], { emoji: '🧢' }),
  ],
  weather: [
    w('weather', 'ˈweðər', 'цаг агаар', 'Noun', [['The weather is nice.', 'Цаг агаар сайхан.']], { emoji: '🌤️' }),
    w('rain', 'reɪn', 'бороо', 'Noun', [['It will rain today.', 'Өнөөдөр бороо орно.']], { emoji: '🌧️' }),
    w('hot', 'hɒt', 'халуун', 'Adjective', [['It is hot today.', 'Өнөөдөр халуун.']], { ant: ['cold'], emoji: '🔥' }),
    w('cold', 'koʊld', 'хүйтэн', 'Adjective', [['It is cold.', 'Хүйтэн байна.']], { ant: ['hot'], emoji: '🥶' }),
  ],
  freetime: [
    w('music', 'ˈmjuːzɪk', 'хөгжим', 'Noun', [['I love music.', 'Би хөгжимд дуртай.']], { emoji: '🎵' }),
    w('game', 'ɡeɪm', 'тоглоом', 'Noun', [['Let us play a game.', 'Тоглоом тоглоё.']], { emoji: '🎮' }),
    w('movie', 'ˈmuːvi', 'кино', 'Noun', [['We watched a movie.', 'Бид кино үзлээ.']], { emoji: '🎬' }),
  ],
  travel: [
    w('airport', 'ˈeəpɔːrt', 'нисэх буудал', 'Noun', [['The airport is far.', 'Буудал хол.']], { emoji: '🛫' }),
    w('hotel', 'hoʊˈtel', 'зочид буудал', 'Noun', [['Our hotel is nice.', 'Манай буудал сайхан.']], { emoji: '🏨' }),
    w('passport', 'ˈpɑːspɔːrt', 'пасспорт', 'Noun', [['Show your passport.', 'Пасспортоо үзүүл.']], { emoji: '🛂' }),
  ],
  emergency: [
    w('help', 'help', 'тусламж', 'Noun', [['Help me, please!', 'Туслаач!']], { emoji: '🆘' }),
    w('police', 'pəˈliːs', 'цагдаа', 'Noun', [['Call the police!', 'Цагдаа дуудаарай!']], { emoji: '👮' }),
    w('fire', 'ˈfaɪər', 'гал', 'Noun', [['There is a fire!', 'Гал гарлаа!']], { emoji: '🔥' }),
  ],
  'irregular-verbs': [
    w('abide', 'əˈbaɪd', 'дагаж мөрдөх', 'Verb', [['We must abide by the rules.', 'Бид дүрмийг дагаж мөрдөх ёстой.']], { id: 'abide', emoji: '📜', past: 'abode/abided', pastParticiple: 'abode/abided/abidden' }),
    w('alight', 'əˈlaɪt', 'буух (тээврээс)', 'Verb', [['The bird alighted on the branch.', 'Шувуу мөчир дээр буув.']], { id: 'alight', emoji: '🕊️', past: 'alit', pastParticiple: 'alit/alighted' }),
    w('arise', 'əˈraɪz', 'гарч ирэх, бий болох', 'Verb', [['A problem may arise.', 'Асуудал гарч болзошгүй.']], { id: 'arise', emoji: '⬆️', past: 'arose', pastParticiple: 'arisen' }),
    w('awake', 'əˈweɪk', 'сэрэх', 'Verb', [['I awoke early.', 'Би эрт сэрлээ.']], { id: 'awake', emoji: '⏰', past: 'awoke', pastParticiple: 'awoken' }),
    w('be', 'biː', 'байх', 'Verb', [['I am happy.', 'Би аз жаргалтай байна.']], { id: 'be', emoji: '🧍', past: 'was/were', pastParticiple: 'been' }),
    w('bear', 'ber', 'тэвчих, тээх', 'Verb', [["I can't bear this noise.", 'Би энэ шуугианыг тэвчихгүй байна.']], { id: 'bear', emoji: '💪', past: 'bore', pastParticiple: 'borne' }),
    w('beat', 'biːt', 'цохих, ялах', 'Verb', [['He beat the drum.', 'Тэр хэнгэрэг цохив.']], { id: 'beat', emoji: '🥁', past: 'beat', pastParticiple: 'beaten' }),
    w('become', 'bɪˈkʌm', 'болох', 'Verb', [['She became a doctor.', 'Тэр эмч болсон.']], { id: 'become', emoji: '🔄', past: 'became', pastParticiple: 'become' }),
    w('begin', 'bɪˈɡɪn', 'эхлэх', 'Verb', [['The movie begins at 8.', 'Кино 8 цагт эхэлнэ.']], { id: 'begin', emoji: '🚀', past: 'began', pastParticiple: 'begun' }),
    w('behold', 'bɪˈhoʊld', 'харах, ажиглах', 'Verb', [['Behold the beauty of nature.', 'Байгалийн үзэсгэлэнг ажигла.']], { id: 'behold', emoji: '👁️', past: 'beheld', pastParticiple: 'beheld' }),
    w('bend', 'bend', 'нугалах', 'Verb', [['Bend your knees.', 'Өвдгөө нугал.']], { id: 'bend', emoji: '🦵', past: 'bent', pastParticiple: 'bent' }),
    w('bet', 'bet', 'мөрийцөх', 'Verb', [['I bet you are right.', 'Чи зөв гэдэгт мөрийцье.']], { id: 'bet', emoji: '🎲', past: 'bet', pastParticiple: 'bet' }),
    w('bid', 'bɪd', 'үнэ хэлэх, ерөөх', 'Verb', [['He bid me farewell.', 'Тэр надтай баяртай гэж хэлэв.']], { id: 'bid', emoji: '🗣️', past: 'bade', pastParticiple: 'bidden' }),
    w('bind', 'baɪnd', 'холбох, уях', 'Verb', [['Bind the papers together.', 'Цаасыг хамт хол.']], { id: 'bind', emoji: '🔗', past: 'bound', pastParticiple: 'bound' }),
    w('bite', 'baɪt', 'хазах', 'Verb', [['The dog bit me.', 'Нохой намайг хазав.']], { id: 'bite', emoji: '🦷', past: 'bit', pastParticiple: 'bitten' }),
    w('bleed', 'bliːd', 'цус гарах', 'Verb', [['My hand is bleeding.', 'Миний гар цуслаж байна.']], { id: 'bleed', emoji: '🩸', past: 'bled', pastParticiple: 'bled' }),
    w('blow', 'bloʊ', 'үлээх', 'Verb', [['The wind blows hard.', 'Салхи хатуу үлээж байна.']], { id: 'blow', emoji: '💨', past: 'blew', pastParticiple: 'blown' }),
    w('break', 'breɪk', 'хугарах', 'Verb', [["Don't break the glass.", 'Шилийг бүү хугал.']], { id: 'break', emoji: '💥', past: 'broke', pastParticiple: 'broken' }),
    w('breed', 'briːd', 'үржүүлэх', 'Verb', [['They breed horses.', 'Тэд адуу үржүүлдэг.']], { id: 'breed', emoji: '🐴', past: 'bred', pastParticiple: 'bred' }),
    w('bring', 'brɪŋ', 'авчрах', 'Verb', [['Bring your book tomorrow.', 'Маргааш номоо авчир.']], { id: 'bring', emoji: '📦', past: 'brought', pastParticiple: 'brought' }),
    w('build', 'bɪld', 'барих', 'Verb', [['They build houses.', 'Тэд байшин барьдаг.']], { id: 'build', emoji: '🏗️', past: 'built', pastParticiple: 'built' }),
    w('burn', 'bɜːrn', 'шатах, шатаах', 'Verb', [['The fire burned all night.', 'Гал бүх шөнөжин шатав.']], { id: 'burn', emoji: '🔥', past: 'burnt', pastParticiple: 'burnt' }),
    w('burst', 'bɜːrst', 'дэлбэрэх', 'Verb', [['The balloon burst.', 'Бөмбөлөг дэлбэрэв.']], { id: 'burst', emoji: '🎈', past: 'burst', pastParticiple: 'burst' }),
    w('bust', 'bʌst', 'эвдэх', 'Verb', [['He busted the door open.', 'Тэр хаалгыг эвдэж онгойлгов.']], { id: 'bust', emoji: '🔨', past: 'bust', pastParticiple: 'bust' }),
    w('buy', 'baɪ', 'худалдан авах', 'Verb', [['I want to buy a car.', 'Би машин авмаар байна.']], { id: 'buy', emoji: '🛍️', past: 'bought', pastParticiple: 'bought' }),
    w('can', 'kæn', 'чадах', 'Verb', [['I can swim.', 'Би сэлж чаддаг.']], { id: 'can', emoji: '💪', past: 'could', pastParticiple: 'been able to' }),
    w('cast', 'kæst', 'шидэх, дүрд оруулах', 'Verb', [['Cast the net into the water.', 'Тороо усанд шид.']], { id: 'cast', emoji: '🎣', past: 'cast', pastParticiple: 'cast' }),
    w('catch', 'kætʃ', 'барих', 'Verb', [['Catch the ball!', 'Бөмбөгийг бариарай!']], { id: 'catch', emoji: '🤲', past: 'caught', pastParticiple: 'caught' }),
    w('choose', 'tʃuːz', 'сонгох', 'Verb', [['Choose one option.', 'Нэг сонголт хий.']], { id: 'choose', emoji: '✅', past: 'chose', pastParticiple: 'chosen' }),
    w('cling', 'klɪŋ', 'наалдах, зуурах', 'Verb', [['The child clung to her mother.', 'Хүүхэд ээждээ наалдав.']], { id: 'cling', emoji: '🤗', past: 'clung', pastParticiple: 'clung' }),
    w('clothe', 'kloʊð', 'хувцаслах', 'Verb', [['She clothed her children warmly.', 'Тэр хүүхдүүдээ дулаан хувцасласан.']], { id: 'clothe', emoji: '🧥', past: 'clad', pastParticiple: 'clad' }),
    w('come', 'kʌm', 'ирэх', 'Verb', [['Come here, please.', 'Энд ир.']], { id: 'come', emoji: '🚶', past: 'came', pastParticiple: 'come' }),
    w('cost', 'kɒst', 'үнэтэй байх', 'Verb', [['This book cost ten dollars.', 'Энэ ном арван доллар үнэтэй.']], { id: 'cost', emoji: '💵', past: 'cost', pastParticiple: 'cost' }),
    w('creep', 'kriːp', 'мөлхөх', 'Verb', [['The cat crept slowly.', 'Муур аажуухан мөлхөв.']], { id: 'creep', emoji: '🐛', past: 'crept', pastParticiple: 'crept' }),
    w('cut', 'kʌt', 'огтлох', 'Verb', [['Cut the bread.', 'Талхыг огтол.']], { id: 'cut', emoji: '✂️', past: 'cut', pastParticiple: 'cut' }),
    w('deal', 'diːl', 'харьцах, хуваарилах', 'Verb', [['I have to deal with this problem.', 'Би энэ асуудалтай харьцах хэрэгтэй.']], { id: 'deal', emoji: '🤝', past: 'dealt', pastParticiple: 'dealt' }),
    w('dig', 'dɪg', 'малтах', 'Verb', [['They dig a hole.', 'Тэд нүх малтдаг.']], { id: 'dig', emoji: '⛏️', past: 'dug', pastParticiple: 'dug' }),
    w('dive', 'daɪv', 'шумбах', 'Verb', [['He dove into the pool.', 'Тэр усан сан руу шумбав.']], { id: 'dive', emoji: '🤿', past: 'dove/dived', pastParticiple: 'dove/dived' }),
    w('do', 'duː', 'хийх', 'Verb', [['I do my homework.', 'Би даалгавраа хийдэг.']], { id: 'do', emoji: '✔️', past: 'did', pastParticiple: 'done' }),
    w('draw', 'drɔː', 'зурах', 'Verb', [['She draws pictures well.', 'Тэр зураг сайн зурдаг.']], { id: 'draw', emoji: '✏️', past: 'drew', pastParticiple: 'drawn' }),
    w('dream', 'driːm', 'мөрөөдөх, зүүд зүүдлэх', 'Verb', [['I dreamt about you.', 'Би чиний тухай зүүдэлсэн.']], { id: 'dream', emoji: '💭', past: 'dreamt', pastParticiple: 'dreamt' }),
    w('drink', 'drɪŋk', 'уух', 'Verb', [['Drink more water.', 'Илүү их ус уу.']], { id: 'drink', emoji: '🥤', past: 'drank', pastParticiple: 'drunk' }),
    w('drive', 'draɪv', 'жолоодох', 'Verb', [['He drives to work.', 'Тэр ажилдаа жолоодож явдаг.']], { id: 'drive', emoji: '🚗', past: 'drove', pastParticiple: 'driven' }),
    w('dwell', 'dwel', 'оршин суух', 'Verb', [['They dwell in the countryside.', 'Тэд хөдөө нутагт амьдардаг.']], { id: 'dwell', emoji: '🏡', past: 'dwelt', pastParticiple: 'dwelt' }),
    w('eat', 'iːt', 'идэх', 'Verb', [['We eat dinner at 7.', 'Бид 7 цагт оройн хоол иддэг.']], { id: 'eat', emoji: '🍽️', past: 'ate', pastParticiple: 'eaten' }),
    w('fall', 'fɔːl', 'унах', 'Verb', [["Be careful, don't fall.", 'Болгоомжтой яв, битгий унаарай.']], { id: 'fall', emoji: '🍂', past: 'fell', pastParticiple: 'fallen' }),
    w('feed', 'fiːd', 'хооллох, тэжээх', 'Verb', [['She feeds the cat every morning.', 'Тэр өглөө бүр муурыг хооллодог.']], { id: 'feed', emoji: '🍼', past: 'fed', pastParticiple: 'fed' }),
    w('feel', 'fiːl', 'мэдрэх', 'Verb', [['I feel happy today.', 'Би өнөөдөр аз жаргалтай байна.']], { id: 'feel', emoji: '💭', past: 'felt', pastParticiple: 'felt' }),
    w('fight', 'faɪt', 'тэмцэх, тулалдах', 'Verb', [['They fought for freedom.', 'Тэд эрх чөлөөний төлөө тэмцсэн.']], { id: 'fight', emoji: '🥊', past: 'fought', pastParticiple: 'fought' }),
    w('find', 'faɪnd', 'олох', 'Verb', [['Did you find your keys?', 'Түлхүүрээ олсон уу?']], { id: 'find', emoji: '🔍', past: 'found', pastParticiple: 'found' }),
    w('fit', 'fɪt', 'тохирох', 'Verb', [['These shoes fit me well.', 'Энэ гутал надад сайн тохирдог.']], { id: 'fit', emoji: '👟', past: 'fit', pastParticiple: 'fit' }),
    w('flee', 'fliː', 'зугтах', 'Verb', [['They fled the country.', 'Тэд улсаас зугтав.']], { id: 'flee', emoji: '🏃', past: 'fled', pastParticiple: 'fled' }),
    w('fling', 'flɪŋ', 'шидэх (хүчтэй)', 'Verb', [['He flung the ball away.', 'Тэр бөмбөгийг хол шидэв.']], { id: 'fling', emoji: '🏐', past: 'flung', pastParticiple: 'flung' }),
    w('fly', 'flaɪ', 'нисэх', 'Verb', [['Birds fly south.', 'Шувууд өмнөө тийш нисдэг.']], { id: 'fly', emoji: '✈️', past: 'flew', pastParticiple: 'flown' }),
    w('forbid', 'fərˈbɪd', 'хориглох', 'Verb', [['I forbid you to go there.', 'Би чамайг тийшээ явахыг хориглож байна.']], { id: 'forbid', emoji: '🚫', past: 'forbade', pastParticiple: 'forbidden' }),
    w('foresee', 'fɔːrˈsiː', 'урьдчилан харах', 'Verb', [['No one could foresee this.', 'Хэн ч үүнийг урьдчилан харж чадаагүй.']], { id: 'foresee', emoji: '🔮', past: 'foresaw', pastParticiple: 'foreseen' }),
    w('forget', 'fərˈɡet', 'мартах', 'Verb', [["Don't forget your bag.", 'Цүнхээ бүү март.']], { id: 'forget', emoji: '🤷', past: 'forgot', pastParticiple: 'forgotten' }),
    w('forgive', 'fərˈgɪv', 'уучлах', 'Verb', [['Please forgive me.', 'Намайг уучлаарай.']], { id: 'forgive', emoji: '🙏', past: 'forgave', pastParticiple: 'forgiven' }),
    w('forsake', 'fərˈseɪk', 'орхих, гээх', 'Verb', [['He forsook his old friends.', 'Тэр хуучин найзуудаа орхив.']], { id: 'forsake', emoji: '💔', past: 'forsook', pastParticiple: 'forsaken' }),
    w('freeze', 'friːz', 'хөлдөх', 'Verb', [['The lake froze in winter.', 'Нуур өвөл хөлдсөн.']], { id: 'freeze', emoji: '❄️', past: 'froze', pastParticiple: 'frozen' }),
    w('frostbite', 'ˈfrɔːstbaɪt', 'хяруу хатгах', 'Verb', [['His fingers were frostbitten.', 'Түүний хуруунууд хяруунд хатгагдсан.']], { id: 'frostbite', emoji: '🥶', past: 'frostbit', pastParticiple: 'frostbitten' }),
    w('get', 'ɡet', 'авах', 'Verb', [['I get up early.', 'Би эрт босдог.']], { id: 'get', emoji: '📥', past: 'got', pastParticiple: 'got' }),
    w('give', 'ɡɪv', 'өгөх', 'Verb', [['Give me your hand.', 'Гараа өг.']], { id: 'give', emoji: '🎁', past: 'gave', pastParticiple: 'given' }),
    w('go', 'ɡoʊ', 'явах', 'Verb', [["Let's go home.", 'Гэр лүүгээ явцгаая.']], { id: 'go', emoji: '🚶‍♂️', past: 'went', pastParticiple: 'gone' }),
    w('grind', 'graɪnd', 'нунтаглах', 'Verb', [['Grind the coffee beans.', 'Кофены буурцгийг нунтагла.']], { id: 'grind', emoji: '☕', past: 'ground', pastParticiple: 'ground' }),
    w('grow', 'ɡroʊ', 'ургах', 'Verb', [['Flowers grow in spring.', 'Цэцэг хавар ургадаг.']], { id: 'grow', emoji: '🌱', past: 'grew', pastParticiple: 'grown' }),
    w('handwrite', 'ˈhændraɪt', 'гараар бичих', 'Verb', [['She handwrote the letter.', 'Тэр захидлыг гараараа бичив.']], { id: 'handwrite', emoji: '✍️', past: 'handwrote', pastParticiple: 'handwritten' }),
    w('hang', 'hæŋ', 'өлгөх', 'Verb', [['Hang your coat here.', 'Пальтоо энд өлг.']], { id: 'hang', emoji: '🧥', past: 'hung', pastParticiple: 'hung' }),
    w('have', 'hæv', 'байх (эзэмших)', 'Verb', [['I have two brothers.', 'Надад хоёр ах бий.']], { id: 'have', emoji: '🤲', past: 'had', pastParticiple: 'had' }),
    w('hear', 'hɪər', 'сонсох', 'Verb', [['Did you hear that noise?', 'Тэр чимээг сонссон уу?']], { id: 'hear', emoji: '👂', past: 'heard', pastParticiple: 'heard' }),
    w('hide', 'haɪd', 'нуух', 'Verb', [['The cat hid under the bed.', 'Муур ор дор нуугдсан.']], { id: 'hide', emoji: '🙈', past: 'hid', pastParticiple: 'hidden' }),
    w('hit', 'hɪt', 'цохих', 'Verb', [['He hit the ball hard.', 'Тэр бөмбөгийг хатуу цохив.']], { id: 'hit', emoji: '⚾', past: 'hit', pastParticiple: 'hit' }),
    w('hold', 'hoʊld', 'барих', 'Verb', [['Hold my hand.', 'Гараас минь бари.']], { id: 'hold', emoji: '✋', past: 'held', pastParticiple: 'held' }),
    w('hurt', 'hɜːrt', 'гэмтээх, өвдөх', 'Verb', [['My leg hurts.', 'Хөл минь өвдөж байна.']], { id: 'hurt', emoji: '🤕', past: 'hurt', pastParticiple: 'hurt' }),
    w('inlay', 'ɪnˈleɪ', 'оруулж чимэх', 'Verb', [['The box is inlaid with gold.', 'Хайрцаг алтаар чимэглэгдсэн.']], { id: 'inlay', emoji: '💎', past: 'inlaid', pastParticiple: 'inlaid' }),
    w('keep', 'kiːp', 'хадгалах', 'Verb', [['Keep this secret.', 'Энэ нууцыг хадгал.']], { id: 'keep', emoji: '🔒', past: 'kept', pastParticiple: 'kept' }),
    w('kneel', 'niːl', 'өвдөг сөгдөх', 'Verb', [['He knelt before the king.', 'Тэр хааны өмнө өвдөг сөгдөв.']], { id: 'kneel', emoji: '🙇', past: 'knelt', pastParticiple: 'knelt' }),
    w('knit', 'nɪt', 'сүлжих', 'Verb', [['Grandma knits sweaters.', 'Эмээ цамц сүлждэг.']], { id: 'knit', emoji: '🧶', past: 'knit', pastParticiple: 'knit' }),
    w('know', 'noʊ', 'мэдэх', 'Verb', [['I know the answer.', 'Би хариултыг мэднэ.']], { id: 'know', emoji: '🧠', past: 'knew', pastParticiple: 'known' }),
    w('lay', 'leɪ', 'тавих, дэвсэх', 'Verb', [['Lay the book on the table.', 'Номоо ширээн дээр тавь.']], { id: 'lay', emoji: '📥', past: 'laid', pastParticiple: 'laid' }),
    w('lead', 'liːd', 'удирдах', 'Verb', [['She leads the team.', 'Тэр багийг удирддаг.']], { id: 'lead', emoji: '🧭', past: 'led', pastParticiple: 'led' }),
    w('lean', 'liːn', 'налах', 'Verb', [['He leaned against the wall.', 'Тэр хананд наалаа.']], { id: 'lean', emoji: '🧱', past: 'leant', pastParticiple: 'leant' }),
    w('leap', 'liːp', 'үсрэх', 'Verb', [['The frog leapt into the pond.', 'Мэлхий цөөрөм рүү үсэрчээ.']], { id: 'leap', emoji: '🐸', past: 'leapt', pastParticiple: 'leapt' }),
    w('learn', 'lɜːrn', 'сурах', 'Verb', [['I learn English every day.', 'Би өдөр бүр англи хэл сурдаг.']], { id: 'learn', emoji: '📚', past: 'learnt', pastParticiple: 'learnt' }),
    w('leave', 'liːv', 'орхих, явах', 'Verb', [['We leave at noon.', 'Бид үд дунд явна.']], { id: 'leave', emoji: '🚪', past: 'left', pastParticiple: 'left' }),
    w('lend', 'lend', 'зээлдүүлэх', 'Verb', [['Can you lend me your pen?', 'Та надад үзгээ зээлдүүлэх үү?']], { id: 'lend', emoji: '🖊️', past: 'lent', pastParticiple: 'lent' }),
    w('let', 'let', 'зөвшөөрөх', 'Verb', [['Let me help you.', 'Надад тусалж болъё.']], { id: 'let', emoji: '🚪', past: 'let', pastParticiple: 'let' }),
    w('lie', 'laɪ', 'хэвтэх', 'Verb', [['He lay on the bed.', 'Тэр ор дээр хэвтэв.']], { id: 'lie', emoji: '🛏️', past: 'lay', pastParticiple: 'lain' }),
    w('light', 'laɪt', 'асаах, гэрэлтүүлэх', 'Verb', [['Light the candle.', 'Лаа асаа.']], { id: 'light', emoji: '🕯️', past: 'lit', pastParticiple: 'lit' }),
    w('lose', 'luːz', 'алдах', 'Verb', [["Don't lose your ticket.", 'Тасалбараа бүү алд.']], { id: 'lose', emoji: '😢', past: 'lost', pastParticiple: 'lost' }),
    w('make', 'meɪk', 'хийх, бүтээх', 'Verb', [['She makes cookies.', 'Тэр жигнэмэг хийдэг.']], { id: 'make', emoji: '🛠️', past: 'made', pastParticiple: 'made' }),
    w('mean', 'miːn', 'гэсэн үг байх', 'Verb', [['What does this word mean?', 'Энэ үг ямар утгатай вэ?']], { id: 'mean', emoji: '💭', past: 'meant', pastParticiple: 'meant' }),
    w('meet', 'miːt', 'уулзах', 'Verb', [['Nice to meet you.', 'Танилцсандаа баяртай.']], { id: 'meet', emoji: '🤝', past: 'met', pastParticiple: 'met' }),
    w('melt', 'melt', 'хайлах', 'Verb', [['The snow melted quickly.', 'Цас хурдан хайлав.']], { id: 'melt', emoji: '🌡️', past: 'melted', pastParticiple: 'molten' }),
    w('mislead', 'mɪsˈliːd', 'төөрөгдүүлэх', 'Verb', [["Don't mislead your customers.", 'Үйлчлүүлэгчээ бүү төөрөгдүүл.']], { id: 'mislead', emoji: '🙅', past: 'misled', pastParticiple: 'misled' }),
    w('mistake', 'mɪˈsteɪk', 'андуурах', 'Verb', [['I mistook you for my friend.', 'Би чамайг найзтайгаа андуурсан.']], { id: 'mistake', emoji: '❓', past: 'mistook', pastParticiple: 'mistaken' }),
    w('misunderstand', 'ˌmɪsʌndərˈstænd', 'буруу ойлгох', 'Verb', [['I misunderstood your question.', 'Би таны асуултыг буруу ойлгосон.']], { id: 'misunderstand', emoji: '😕', past: 'misunderstood', pastParticiple: 'misunderstood' }),
    w('mow', 'moʊ', 'хадах, тайрах', 'Verb', [['He mows the lawn every week.', '7 хоног бүр өвсөө хадна.']], { id: 'mow', emoji: '🌾', past: 'mowed', pastParticiple: 'mown' }),
    w('overdraw', 'ˌoʊvərˈdrɔː', 'дансаа хэтрүүлэх', 'Verb', [['I overdrew my account.', 'Би дансаа хэтрүүлэв.']], { id: 'overdraw', emoji: '🏦', past: 'overdrew', pastParticiple: 'overdrawn' }),
    w('overhear', 'ˌoʊvərˈhɪr', 'санамсаргүй сонсох', 'Verb', [['I overheard their conversation.', 'Би тэдний яриаг санамсаргүй сонссон.']], { id: 'overhear', emoji: '👂', past: 'overheard', pastParticiple: 'overheard' }),
    w('overtake', 'ˌoʊvərˈteɪk', 'гүйцэж түрүүлэх', 'Verb', [['The car overtook us.', 'Машин биднийг гүйцэж түрүүлэв.']], { id: 'overtake', emoji: '🚗', past: 'overtook', pastParticiple: 'overtaken' }),
    w('pay', 'peɪ', 'төлөх', 'Verb', [['I pay by card.', 'Би картаар төлдөг.']], { id: 'pay', emoji: '💳', past: 'paid', pastParticiple: 'paid' }),
    w('preset', 'priːˈset', 'урьдчилан тохируулах', 'Verb', [['The timer is preset for ten minutes.', 'Таймер 10 минутаар урьдчилан тохируулагдсан.']], { id: 'preset', emoji: '⏱️', past: 'preset', pastParticiple: 'preset' }),
    w('prove', 'pruːv', 'нотлох', 'Verb', [['Can you prove it?', 'Та үүнийг нотолж чадах уу?']], { id: 'prove', emoji: '✅', past: 'proved', pastParticiple: 'proven' }),
    w('put', 'pʊt', 'тавих', 'Verb', [['Put it on the table.', 'Ширээн дээр тавь.']], { id: 'put', emoji: '📍', past: 'put', pastParticiple: 'put' }),
    w('quit', 'kwɪt', 'орхих, гарах', 'Verb', [['He quit his job.', 'Тэр ажлаа орхив.']], { id: 'quit', emoji: '🚪', past: 'quit', pastParticiple: 'quit' }),
    w('read', 'riːd', 'унших', 'Verb', [['I read every night.', 'Би шөнө бүр ном уншдаг.']], { id: 'read', emoji: '📖', past: 'read', pastParticiple: 'read' }),
    w('rid', 'rɪd', 'чөлөөлөх, ангижрах', 'Verb', [['We got rid of the old furniture.', 'Бид хуучин тавилгаас ангижрав.']], { id: 'rid', emoji: '🗑️', past: 'rid', pastParticiple: 'rid' }),
    w('ride', 'raɪd', 'унах (унаа)', 'Verb', [['He rides a bike.', 'Тэр дугуй унадаг.']], { id: 'ride', emoji: '🚴', past: 'rode', pastParticiple: 'ridden' }),
    w('ring', 'rɪŋ', 'дуугарах (хонх)', 'Verb', [['The phone rang loudly.', 'Утас чанга дуугарав.']], { id: 'ring', emoji: '🔔', past: 'rang', pastParticiple: 'rung' }),
    w('rise', 'raɪz', 'мандах, өсөх', 'Verb', [['The sun rises in the east.', 'Нар зүүнээс мандана.']], { id: 'rise', emoji: '🌅', past: 'rose', pastParticiple: 'risen' }),
    w('rive', 'raɪv', 'хагалах, урах', 'Verb', [['Grief rived his heart.', 'Уй гуниг зүрхийг нь урав.']], { id: 'rive', emoji: '💔', past: 'rived', pastParticiple: 'riven' }),
    w('run', 'rʌn', 'гүйх', 'Verb', [['She runs every morning.', 'Тэр өглөө бүр гүйдэг.']], { id: 'run', emoji: '🏃', past: 'ran', pastParticiple: 'run' }),
    w('saw', 'sɔː', 'хөрөөдөх', 'Verb', [['He sawed the wood.', 'Тэр модыг хөрөөдөв.']], { id: 'saw', emoji: '🪚', past: 'sawed', pastParticiple: 'sawn' }),
    w('say', 'seɪ', 'хэлэх', 'Verb', [['What did you say?', 'Та юу гэж хэлэв?']], { id: 'say', emoji: '💬', past: 'said', pastParticiple: 'said' }),
    w('see', 'siː', 'харах', 'Verb', [['I see a bird.', 'Би шувуу хараа байна.']], { id: 'see', emoji: '👀', past: 'saw', pastParticiple: 'seen' }),
    w('seek', 'siːk', 'хайх, эрэлхийлэх', 'Verb', [['They seek a better life.', 'Тэд илүү сайхан амьдралыг эрэлхийлдэг.']], { id: 'seek', emoji: '🔎', past: 'sought', pastParticiple: 'sought' }),
    w('sell', 'sel', 'зарах', 'Verb', [['They sell fruit.', 'Тэд жимс зардаг.']], { id: 'sell', emoji: '🏷️', past: 'sold', pastParticiple: 'sold' }),
    w('send', 'send', 'илгээх', 'Verb', [['Send me an email.', 'Надад имэйл илгээ.']], { id: 'send', emoji: '📤', past: 'sent', pastParticiple: 'sent' }),
    w('set', 'set', 'тавих, тохируулах', 'Verb', [['Set the table for dinner.', 'Оройн хоолны ширээ засаарай.']], { id: 'set', emoji: '🍽️', past: 'set', pastParticiple: 'set' }),
    w('sew', 'soʊ', 'оёх', 'Verb', [['She sews her own clothes.', 'Тэр өөрийн хувцсаа оёдог.']], { id: 'sew', emoji: '🧵', past: 'sewed', pastParticiple: 'sewn' }),
    w('shake', 'ʃeɪk', 'сэгсрэх, доргих', 'Verb', [['Shake the bottle well.', 'Лонхыг сайн сэгсэр.']], { id: 'shake', emoji: '🫨', past: 'shook', pastParticiple: 'shaken' }),
    w('shave', 'ʃeɪv', 'сахлаа хусах', 'Verb', [['He shaves every morning.', 'Тэр өглөө бүр сахлаа хусдаг.']], { id: 'shave', emoji: '🪒', past: 'shaved', pastParticiple: 'shaven' }),
    w('shear', 'ʃɪr', 'хяргах (ноос)', 'Verb', [['They shear the sheep in spring.', 'Тэд хаварт хониноос ноос хяргадаг.']], { id: 'shear', emoji: '🐑', past: 'shore', pastParticiple: 'shorn' }),
    w('shed', 'ʃed', 'хаях, урсгах', 'Verb', [['The dog sheds its fur.', 'Нохой үс хаядаг.']], { id: 'shed', emoji: '🐕', past: 'shed', pastParticiple: 'shed' }),
    w('shine', 'ʃaɪn', 'гэрэлтэх', 'Verb', [['The sun shone brightly.', 'Нар тод гэрэлтэв.']], { id: 'shine', emoji: '☀️', past: 'shone', pastParticiple: 'shone' }),
    w('shoe', 'ʃuː', 'тавагтай хийх', 'Verb', [['The blacksmith shod the horse.', 'Дархан морийг тавагтай болгов.']], { id: 'shoe', emoji: '🐴', past: 'shod', pastParticiple: 'shod' }),
    w('shoot', 'ʃuːt', 'буудах', 'Verb', [['He shot an arrow.', 'Тэр сум буудав.']], { id: 'shoot', emoji: '🏹', past: 'shot', pastParticiple: 'shot' }),
    w('show', 'ʃoʊ', 'үзүүлэх', 'Verb', [['Show me your work.', 'Ажлаа надад үзүүл.']], { id: 'show', emoji: '👀', past: 'showed', pastParticiple: 'shown' }),
    w('shrink', 'ʃrɪŋk', 'агших, багасах', 'Verb', [['The shirt shrank in the wash.', 'Цамц угаахад агшив.']], { id: 'shrink', emoji: '👕', past: 'shrank', pastParticiple: 'shrunk' }),
    w('shut', 'ʃʌt', 'хаах', 'Verb', [['Shut the window, please.', 'Цонхоо хаагаарай.']], { id: 'shut', emoji: '🪟', past: 'shut', pastParticiple: 'shut' }),
    w('sing', 'sɪŋ', 'дуулах', 'Verb', [['She sings beautifully.', 'Тэр сайхан дуулдаг.']], { id: 'sing', emoji: '🎤', past: 'sang', pastParticiple: 'sung' }),
    w('sink', 'sɪŋk', 'живэх', 'Verb', [['The ship sank slowly.', 'Хөлөг аажим живэв.']], { id: 'sink', emoji: '🚢', past: 'sank', pastParticiple: 'sunk' }),
    w('sit', 'sɪt', 'суух', 'Verb', [['Please sit down.', 'Сууна уу.']], { id: 'sit', emoji: '🪑', past: 'sat', pastParticiple: 'sat' }),
    w('slay', 'sleɪ', 'хороох, устгах', 'Verb', [['The knight slew the dragon.', 'Баатар луу хороов.']], { id: 'slay', emoji: '⚔️', past: 'slew', pastParticiple: 'slain' }),
    w('sleep', 'sliːp', 'унтах', 'Verb', [['I sleep eight hours.', 'Би найман цаг унтдаг.']], { id: 'sleep', emoji: '😴', past: 'slept', pastParticiple: 'slept' }),
    w('slide', 'slaɪd', 'гулгах', 'Verb', [['Children slid down the hill.', 'Хүүхдүүд толгодоос гулгав.']], { id: 'slide', emoji: '🛝', past: 'slid', pastParticiple: 'slid' }),
    w('sling', 'slɪŋ', 'шидэх, зүүх', 'Verb', [['He slung his bag over his shoulder.', 'Тэр цүнхээ мөрөндөө зүүв.']], { id: 'sling', emoji: '🎒', past: 'slung', pastParticiple: 'slung' }),
    w('slink', 'slɪŋk', 'хулгайгаар явах', 'Verb', [['The cat slunk away.', 'Муур чимээгүй зайлав.']], { id: 'slink', emoji: '🐈', past: 'slunk', pastParticiple: 'slunk' }),
    w('slit', 'slɪt', 'нарийн зүсэх', 'Verb', [['He slit the envelope open.', 'Тэр дугтуйг нарийн зүсэж онгойлгов.']], { id: 'slit', emoji: '✂️', past: 'slit', pastParticiple: 'slit' }),
    w('smell', 'smel', 'үнэрлэх', 'Verb', [['This flower smells sweet.', 'Энэ цэцэг сайхан үнэртэй.']], { id: 'smell', emoji: '👃', past: 'smelt', pastParticiple: 'smelt' }),
    w('sneak', 'sniːk', 'чимээгүй орох', 'Verb', [['He snuck into the room.', 'Тэр өрөө рүү чимээгүй ороов.']], { id: 'sneak', emoji: '🤫', past: 'snuck', pastParticiple: 'snuck' }),
    w('sow', 'soʊ', 'тарих (үр)', 'Verb', [['Farmers sow seeds in spring.', 'Тариаланчид хаварт үр тардаг.']], { id: 'sow', emoji: '🌾', past: 'sowed', pastParticiple: 'sown' }),
    w('speak', 'spiːk', 'ярих', 'Verb', [['Do you speak English?', 'Та англиар ярьдаг уу?']], { id: 'speak', emoji: '🗣️', past: 'spoke', pastParticiple: 'spoken' }),
    w('speed', 'spiːd', 'хурдлах', 'Verb', [['He was speeding down the road.', 'Тэр замаар хурдлан явж байсан.']], { id: 'speed', emoji: '🏎️', past: 'sped', pastParticiple: 'sped' }),
    w('spell', 'spel', 'үсэглэх', 'Verb', [['Can you spell your name?', 'Та нэрээ үсэглэж чадах уу?']], { id: 'spell', emoji: '🔤', past: 'spelt', pastParticiple: 'spelt' }),
    w('spend', 'spend', 'зарцуулах', 'Verb', [['I spend money on books.', 'Би номонд мөнгө зарцуулдаг.']], { id: 'spend', emoji: '💸', past: 'spent', pastParticiple: 'spent' }),
    w('spill', 'spɪl', 'асгах, асгарах', 'Verb', [['I spilled my coffee.', 'Би кофеоо асгачихлаа.']], { id: 'spill', emoji: '☕', past: 'spilt', pastParticiple: 'spilt' }),
    w('spin', 'spɪn', 'эргэх, эрүүлэх', 'Verb', [['The wheel spun fast.', 'Дугуй хурдан эргэв.']], { id: 'spin', emoji: '🌀', past: 'span', pastParticiple: 'spun' }),
    w('spit', 'spɪt', 'нулимах', 'Verb', [["Don't spit on the ground.", 'Газарт бүү нулим.']], { id: 'spit', emoji: '🤮', past: 'spat', pastParticiple: 'spat' }),
    w('split', 'splɪt', 'хуваах', 'Verb', [["Let's split the bill.", 'Тооцоогоо хуваацгаая.']], { id: 'split', emoji: '➗', past: 'split', pastParticiple: 'split' }),
    w('spoil', 'spɔɪl', 'муутгах, эвдэх', 'Verb', [["Don't spoil the surprise.", 'Гайхшралыг бүү сүйт.']], { id: 'spoil', emoji: '🎁', past: 'spoilt', pastParticiple: 'spoilt' }),
    w('spread', 'spred', 'тарах, дэлгэх', 'Verb', [['The news spread quickly.', 'Мэдээ хурдан тарав.']], { id: 'spread', emoji: '📰', past: 'spread', pastParticiple: 'spread' }),
    w('spring', 'sprɪŋ', 'үсрэх, тэсрэх', 'Verb', [['He sprang out of bed.', 'Тэр ороосоо тэсрэн босов.']], { id: 'spring', emoji: '🦘', past: 'sprang', pastParticiple: 'sprung' }),
    w('stand', 'stænd', 'зогсох', 'Verb', [['Stand up, please.', 'Босож зогсооно уу.']], { id: 'stand', emoji: '🧍‍♂️', past: 'stood', pastParticiple: 'stood' }),
    w('steal', 'stiːl', 'хулгайлах', 'Verb', [['Someone stole my bike.', 'Хэн нэгэн миний дугуй хулгайлав.']], { id: 'steal', emoji: '🕵️', past: 'stole', pastParticiple: 'stolen' }),
    w('stick', 'stɪk', 'наах, наалдах', 'Verb', [['The stamp stuck to the envelope.', 'Марк дугтуйнд наалдав.']], { id: 'stick', emoji: '📎', past: 'stuck', pastParticiple: 'stuck' }),
    w('sting', 'stɪŋ', 'хатгах (шавьж)', 'Verb', [['A bee stung me.', 'Зөгий намайг хатгав.']], { id: 'sting', emoji: '🐝', past: 'stung', pastParticiple: 'stung' }),
    w('stink', 'stɪŋk', 'муухай үнэртэх', 'Verb', [['The fish stank badly.', 'Загас маш муухай үнэртэв.']], { id: 'stink', emoji: '🤢', past: 'stank', pastParticiple: 'stunk' }),
    w('stride', 'straɪd', 'том алхаж явах', 'Verb', [['He strode across the room.', 'Тэр өрөөгөөр том алхмаар алхав.']], { id: 'stride', emoji: '🚶', past: 'strode', pastParticiple: 'stridden' }),
    w('strike', 'straɪk', 'цохих, ажил хаях', 'Verb', [['Lightning struck the tree.', 'Аянга модонд цохив.']], { id: 'strike', emoji: '⚡', past: 'struck', pastParticiple: 'struck' }),
    w('string', 'strɪŋ', 'утаслах, холбох', 'Verb', [['She strung the beads together.', 'Тэр сувдыг хамт холбов.']], { id: 'string', emoji: '📿', past: 'strung', pastParticiple: 'strung' }),
    w('strip', 'strɪp', 'тайлах, хуулах', 'Verb', [['He stripped the paint off the wall.', 'Тэр ханан дахь будгийг хуулав.']], { id: 'strip', emoji: '🎨', past: 'stripped/stript', pastParticiple: 'stripped/stript' }),
    w('strive', 'straɪv', 'хичээх, зүтгэх', 'Verb', [['We strive for excellence.', 'Бид оргилд хүрэхийн төлөө зүтгэдэг.']], { id: 'strive', emoji: '💪', past: 'strove', pastParticiple: 'striven' }),
    w('sublet', 'ˌsʌbˈlet', 'дэд түрээслэх', 'Verb', [['She sublet her apartment.', 'Тэр байрандаа дэд түрээслэгч оруулав.']], { id: 'sublet', emoji: '🏢', past: 'sublet', pastParticiple: 'sublet' }),
    w('sunburn', 'ˈsʌnbɜːrn', 'нартай түлэгдэх', 'Verb', [['I got sunburnt at the beach.', 'Би далайн эрэг дээр нартай түлэгдэв.']], { id: 'sunburn', emoji: '🏖️', past: 'sunburnt', pastParticiple: 'sunburnt' }),
    w('swear', 'swer', 'тангараглах, хараах', 'Verb', [["I swear I didn't do it.", 'Би үүнийг хийгээгүй гэдгээ тангараглая.']], { id: 'swear', emoji: '🤞', past: 'swore', pastParticiple: 'sworn' }),
    w('sweat', 'swet', 'хөлрөх', 'Verb', [['He sweats a lot when running.', 'Тэр гүйхдээ их хөлрдөг.']], { id: 'sweat', emoji: '💦', past: 'sweat', pastParticiple: 'sweat' }),
    w('sweep', 'swiːp', 'шүүрдэх', 'Verb', [['She swept the floor.', 'Тэр шалыг шүүрдэв.']], { id: 'sweep', emoji: '🧹', past: 'swept', pastParticiple: 'swept' }),
    w('swell', 'swel', 'хавдах', 'Verb', [['His leg swelled after the injury.', 'Гэмтсэний дараа хөл нь хавдав.']], { id: 'swell', emoji: '🦵', past: 'swelled', pastParticiple: 'swollen' }),
    w('swim', 'swɪm', 'сэлэх', 'Verb', [['We swim in summer.', 'Бид зун сэлдэг.']], { id: 'swim', emoji: '🏊', past: 'swam', pastParticiple: 'swum' }),
    w('swing', 'swɪŋ', 'савлах, найгах', 'Verb', [['Children love to swing.', 'Хүүхдүүд савлахад дуртай.']], { id: 'swing', emoji: '🤸', past: 'swung', pastParticiple: 'swung' }),
    w('take', 'teɪk', 'авах', 'Verb', [['Take this book.', 'Энэ номыг ав.']], { id: 'take', emoji: '🤏', past: 'took', pastParticiple: 'taken' }),
    w('teach', 'tiːtʃ', 'заах', 'Verb', [['She teaches math.', 'Тэр математик заадаг.']], { id: 'teach', emoji: '👩‍🏫', past: 'taught', pastParticiple: 'taught' }),
    w('tear', 'ter', 'урах', 'Verb', [['He tore the paper in half.', 'Тэр цаасыг хагасд хуваан урав.']], { id: 'tear', emoji: '📄', past: 'tore', pastParticiple: 'torn' }),
    w('tell', 'tel', 'хэлэх', 'Verb', [['Tell me a story.', 'Надад үлгэр ярь.']], { id: 'tell', emoji: '🗨️', past: 'told', pastParticiple: 'told' }),
    w('think', 'θɪŋk', 'бодох', 'Verb', [["I think you're right.", 'Би чиний зөв гэж бодож байна.']], { id: 'think', emoji: '🤔', past: 'thought', pastParticiple: 'thought' }),
    w('thrive', 'θraɪv', 'хөгжих, цэцэглэх', 'Verb', [['The business thrived last year.', 'Бизнес өнгөрсөн жил цэцэглэсэн.']], { id: 'thrive', emoji: '📈', past: 'throve', pastParticiple: 'thriven' }),
    w('throw', 'θroʊ', 'шидэх', 'Verb', [['Throw the ball to me.', 'Бөмбөгийг над руу шид.']], { id: 'throw', emoji: '🏀', past: 'threw', pastParticiple: 'thrown' }),
    w('thrust', 'θrʌst', 'түлхэх, шургуулах', 'Verb', [['He thrust the key into the lock.', 'Тэр түлхүүрийг цоожинд шургуулав.']], { id: 'thrust', emoji: '🗝️', past: 'thrust', pastParticiple: 'thrust' }),
    w('tread', 'tred', 'гишгэх', 'Verb', [['Tread carefully on the ice.', 'Мөс дээр болгоомжтой гиш.']], { id: 'tread', emoji: '👣', past: 'trod', pastParticiple: 'trodden' }),
    w('undergo', 'ˌʌndərˈɡoʊ', 'туулах, өнгөрүүлэх', 'Verb', [['She underwent surgery.', 'Тэр мэс засал хийлгэв.']], { id: 'undergo', emoji: '🏥', past: 'underwent', pastParticiple: 'undergone' }),
    w('understand', 'ˌʌndərˈstænd', 'ойлгох', 'Verb', [['I understand now.', 'Би одоо ойлгож байна.']], { id: 'understand', emoji: '💡', past: 'understood', pastParticiple: 'understood' }),
    w('undertake', 'ˌʌndərˈteɪk', 'хариуцах, эрхлэх', 'Verb', [['He undertook a difficult task.', 'Тэр хэцүү даалгавар хариуцав.']], { id: 'undertake', emoji: '📋', past: 'undertook', pastParticiple: 'undertaken' }),
    w('upset', 'ʌpˈset', 'уурлуулах, гунигтуулах', 'Verb', [['The news upset her.', 'Мэдээ түүнийг гунигтуулав.']], { id: 'upset', emoji: '😢', past: 'upset', pastParticiple: 'upset' }),
    w('vex', 'veks', 'бухимдуулах', 'Verb', [['The noise vexed him.', 'Чимээ түүнийг бухимдуулав.']], { id: 'vex', emoji: '😤', past: 'vext/vexed', pastParticiple: 'vext/vexed' }),
    w('wake', 'weɪk', 'сэрэх', 'Verb', [['I wake up at 6.', 'Би 6 цагт сэрдэг.']], { id: 'wake', emoji: '⏰', past: 'woke', pastParticiple: 'woken' }),
    w('wear', 'wer', 'өмсөх', 'Verb', [['She wears a blue dress.', 'Тэр цэнхэр даашинз өмссөн.']], { id: 'wear', emoji: '👗', past: 'wore', pastParticiple: 'worn' }),
    w('weave', 'wiːv', 'нэхэх', 'Verb', [['She weaves beautiful carpets.', 'Тэр үзэсгэлэнтэй хивс нэхдэг.']], { id: 'weave', emoji: '🧵', past: 'wove', pastParticiple: 'woven' }),
    w('wed', 'wed', 'гэрлэх', 'Verb', [['They wed last summer.', 'Тэд өнгөрсөн зун гэрлэсэн.']], { id: 'wed', emoji: '💍', past: 'wed', pastParticiple: 'wed' }),
    w('weep', 'wiːp', 'уйлах', 'Verb', [['She wept with joy.', 'Тэр баяртайгаа уйлав.']], { id: 'weep', emoji: '😭', past: 'wept', pastParticiple: 'wept' }),
    w('wend', 'wend', 'явах, чиглэх', 'Verb', [['We wended our way home.', 'Бид гэр лүүгээ чиглэн явлаа.']], { id: 'wend', emoji: '🚶‍♀️', past: 'went', pastParticiple: 'went' }),
    w('wet', 'wet', 'норгох', 'Verb', [["Don't wet the carpet.", 'Хивсийг бүү норго.']], { id: 'wet', emoji: '💧', past: 'wet', pastParticiple: 'wet' }),
    w('win', 'wɪn', 'ялах', 'Verb', [['Our team won the game.', 'Манай баг тоглолтод ялсан.']], { id: 'win', emoji: '🏆', past: 'won', pastParticiple: 'won' }),
    w('wind', 'waɪnd', 'ороох, мушгих', 'Verb', [['Wind the rope around the pole.', 'Олсыг шонгийн эргэн тойрон ороо.']], { id: 'wind', emoji: '🧵', past: 'wound', pastParticiple: 'wound' }),
    w('withdraw', 'wɪðˈdrɔː', 'татан авах', 'Verb', [['I withdrew money from the bank.', 'Би банкнаас мөнгө татан авав.']], { id: 'withdraw', emoji: '🏧', past: 'withdrew', pastParticiple: 'withdrawn' }),
    w('withhold', 'wɪðˈhoʊld', 'нуух, өгөхгүй байх', 'Verb', [['He withheld the information.', 'Тэр мэдээллийг нуув.']], { id: 'withhold', emoji: '🤐', past: 'withheld', pastParticiple: 'withheld' }),
    w('withstand', 'wɪðˈstænd', 'тэсвэрлэх', 'Verb', [['The bridge withstood the storm.', 'Гүүр шуургыг тэсвэрлэв.']], { id: 'withstand', emoji: '🌉', past: 'withstood', pastParticiple: 'withstood' }),
    w('wring', 'rɪŋ', 'шахах, мушгих', 'Verb', [['Wring out the wet towel.', 'Норсон алчуурыг шахаж хат.']], { id: 'wring', emoji: '🧻', past: 'wrung', pastParticiple: 'wrung' }),
    w('write', 'raɪt', 'бичих', 'Verb', [['I write in my diary.', 'Би өдрийн тэмдэглэлдээ бичдэг.']], { id: 'write', emoji: '✍️', past: 'wrote', pastParticiple: 'written' }),
    w('zinc', 'zɪŋk', 'цайрлах', 'Verb', [['The metal was zincked to prevent rust.', 'Ган зэвэрхээс сэргийлж цайрлагдсан.']], { id: 'zinc', emoji: '⚙️', past: 'zincked', pastParticiple: 'zincked' }),
  ],
};

// ── CHINESE (primary) ──
const ZH = {
  greetings: [
    w('你好', 'nǐ hǎo', 'сайн уу', 'Мэндчилгээ', [['你好！你好吗？', 'Сайн уу! Сайн байна уу?']], { rel: ['谢谢', '再见'], mn: '你 (чи) + 好 (сайн) = сайн уу', emoji: '👋' }),
    w('再见', 'zài jiàn', 'баяртай', 'Мэндчилгээ', [['再见，明天见！', 'Баяртай, маргааш уулзъя!']], { ant: ['你好'], emoji: '👋' }),
    w('谢谢', 'xiè xie', 'баярлалаа', 'Мэндчилгээ', [['谢谢你的帮助。', 'Тусалсанд баярлалаа.']], { rel: ['不客气'], emoji: '🙏' }),
    w('对不起', 'duì bu qǐ', 'уучлаарай', 'Мэндчилгээ', [['对不起，我迟到了。', 'Уучлаарай, хоцорлоо.']], { emoji: '😔' }),
    w('请', 'qǐng', 'гуйя', 'Үйл үг', [['请坐。', 'Сууна уу.']], { emoji: '🙏' }),
    w('早上好', 'zǎo shang hǎo', 'өглөөний мэнд', 'Мэндчилгээ', [['早上好，老师！', 'Өглөөний мэнд, багш аа!']], { emoji: '🌅' }),
    w('晚上好', 'wǎn shang hǎo', 'оройн мэнд', 'Мэндчилгээ', [['晚上好！', 'Оройн мэнд!']], { emoji: '🌙' }),
    w('不客气', 'bú kè qi', 'зүгээр (хариу)', 'Мэндчилгээ', [['不客气！', 'Зүгээр зүгээр!']], { rel: ['谢谢'], emoji: '🙂' }),
    w('没关系', 'méi guān xi', 'хамаагүй', 'Мэндчилгээ', [['没关系。', 'Зүгээр, хамаагүй.']], { emoji: '👌' }),
    w('欢迎', 'huān yíng', 'тавтай морил', 'Мэндчилгээ', [['欢迎你！', 'Тавтай морил!']], { emoji: '🎉' }),
  ],
  introductions: [
    w('名字', 'míng zi', 'нэр', 'Нэр үг', [['我的名字是巴特。', 'Миний нэр Бат.']], { emoji: '📛' }),
    w('他', 'tā', 'тэр (эр)', 'Төлөөний үг', [['他是医生。', 'Тэр эмч.']], { emoji: '👨' }),
    w('她', 'tā', 'тэр (эм)', 'Төлөөний үг', [['她是老师。', 'Тэр багш.']], { emoji: '👩' }),
    w('岁', 'suì', 'нас', 'Нэр үг', [['我二十岁。', 'Би хорин настай.']], { emoji: '🎂' }),
    w('国家', 'guó jiā', 'улс', 'Нэр үг', [['你来自哪个国家？', 'Чи аль улсаас ирсэн бэ?']], { emoji: '🌍' }),
    w('认识', 'rèn shi', 'танилцах', 'Үйл үг', [['认识你很高兴。', 'Танилцсандаа баяртай байна.']], { emoji: '🤝' }),
    w('我', 'wǒ', 'би', 'Төлөөний үг', [['我是学生。', 'Би оюутан.']], { rel: ['你', '他'], emoji: '🙋' }),
    w('你', 'nǐ', 'чи', 'Төлөөний үг', [['你好吗？', 'Чи сайн уу?']], { rel: ['我'], emoji: '👉' }),
    w('朋友', 'péng you', 'найз', 'Нэр үг', [['他是我的朋友。', 'Тэр миний найз.']], { emoji: '🤝' }),
  ],
  family: [
    w('妈妈', 'mā ma', 'ээж', 'Нэр үг', [['我妈妈是老师。', 'Миний ээж багш.']], { ant: ['爸爸'], emoji: '👩' }),
    w('爸爸', 'bà ba', 'аав', 'Нэр үг', [['爸爸在工作。', 'Аав ажиллаж байна.']], { ant: ['妈妈'], emoji: '👨' }),
    w('姐姐', 'jiě jie', 'эгч', 'Нэр үг', [['我有一个姐姐。', 'Надад нэг эгчтэй.']], { ant: ['哥哥'], emoji: '👧' }),
    w('哥哥', 'gē ge', 'ах', 'Нэр үг', [['我哥哥很高。', 'Миний ах өндөр.']], { ant: ['姐姐'], emoji: '👦' }),
    w('弟弟', 'dì di', 'дүү (эр)', 'Нэр үг', [['这是我弟弟。', 'Энэ миний дүү.']], { emoji: '👦' }),
    w('妹妹', 'mèi mei', 'дүү (эм)', 'Нэр үг', [['我有一个妹妹。', 'Надад нэг дүү бий.']], { emoji: '👧' }),
    w('爷爷', 'yé ye', 'өвөө', 'Нэр үг', [['爷爷很老。', 'Өвөө хөгшин.']], { emoji: '👴' }),
    w('奶奶', 'nǎi nai', 'эмээ', 'Нэр үг', [['奶奶做饭。', 'Эмээ хоол хийдэг.']], { emoji: '👵' }),
    w('孩子', 'hái zi', 'хүүхэд', 'Нэр үг', [['孩子在玩。', 'Хүүхэд тоглож байна.']], { emoji: '🧒' }),
  ],
  home: [
    w('家', 'jiā', 'гэр', 'Нэр үг', [['这是我的家。', 'Энэ миний гэр.']], { emoji: '🏠' }),
    w('门', 'mén', 'хаалга', 'Нэр үг', [['请开门。', 'Хаалгаа онгойлго.']], { emoji: '🚪' }),
    w('桌子', 'zhuō zi', 'ширээ', 'Нэр үг', [['书在桌子上。', 'Ном ширээн дээр.']], { emoji: '🪑' }),
    w('床', 'chuáng', 'ор', 'Нэр үг', [['我在床上睡觉。', 'Би ороороо унтдаг.']], { emoji: '🛏️' }),
    w('窗', 'chuāng', 'цонх', 'Нэр үг', [['请开窗。', 'Цонхоо онгойлго.']], { emoji: '🪟' }),
    w('厨房', 'chú fáng', 'гал тогоо', 'Нэр үг', [['妈妈在厨房。', 'Ээж гал тогоонд байна.']], { emoji: '🍳' }),
    w('厕所', 'cè suǒ', 'жорлон', 'Нэр үг', [['厕所在哪里？', 'Жорлон хаана байна?']], { emoji: '🚻' }),
    w('椅子', 'yǐ zi', 'сандал', 'Нэр үг', [['坐在椅子上。', 'Сандал дээр суу.']], { emoji: '🪑' }),
  ],
  food: [
    w('吃', 'chī', 'идэх', 'Үйл үг', [['我们一起吃饭。', 'Хамт хооллоё.']], { emoji: '🍽️' }),
    w('水', 'shuǐ', 'ус', 'Нэр үг', [['我每天喝水。', 'Би өдөр бүр ус уудаг.']], { emoji: '💧' }),
    w('米饭', 'mǐ fàn', 'будаа', 'Нэр үг', [['我要炒饭。', 'Би шарсан будаа авна.']], { emoji: '🍚' }),
    w('茶', 'chá', 'цай', 'Нэр үг', [['她喜欢绿茶。', 'Тэр ногоон цайнд дуртай.']], { emoji: '🍵' }),
    w('咖啡', 'kā fēi', 'кофе', 'Нэр үг', [['一杯咖啡。', 'Нэг кофе.']], { emoji: '☕' }),
    w('面包', 'miàn bāo', 'талх', 'Нэр үг', [['我喜欢面包。', 'Би талханд дуртай.']], { emoji: '🍞' }),
    w('鸡蛋', 'jī dàn', 'өндөг', 'Нэр үг', [['两个鸡蛋。', 'Хоёр өндөг.']], { emoji: '🥚' }),
    w('牛奶', 'niú nǎi', 'сүү', 'Нэр үг', [['我每天喝牛奶。', 'Би өдөр бүр сүү уудаг.']], { emoji: '🥛' }),
    w('水果', 'shuǐ guǒ', 'жимс', 'Нэр үг', [['我喜欢吃水果。', 'Би жимс идэх дуртай.']], { emoji: '🍎' }),
    w('好吃', 'hǎo chī', 'амттай', 'Тэмдэг нэр', [['这个很好吃。', 'Энэ маш амттай.']], { emoji: '😋' }),
    w('饿', 'è', 'өлсөх', 'Тэмдэг нэр', [['我饿了。', 'Би өлсөж байна.']], { emoji: '🍽️' }),
  ],
  shopping: [
    w('价格', 'jià gé', 'үнэ', 'Нэр үг', [['这个多少钱？', 'Энэ ямар үнэтэй вэ?'], ['价格太高了。', 'Үнэ хэт өндөр.']], { syn: ['钱'], rel: ['贵', '便宜', '买'], emoji: '🏷️' }),
    w('多少', 'duō shao', 'хэд', 'Асуух', [['多少钱？', 'Хэдэн төгрөг вэ?']], { emoji: '🔢' }),
    w('打折', 'dǎ zhé', 'хямдрал', 'Нэр үг', [['现在打折。', 'Одоо хямдралтай.']], { emoji: '🏷️' }),
    w('颜色', 'yán sè', 'өнгө', 'Нэр үг', [['我喜欢这个颜色。', 'Би энэ өнгөнд дуртай.']], { emoji: '🎨' }),
    w('大小', 'dà xiǎo', 'хэмжээ', 'Нэр үг', [['你穿什么大小？', 'Та ямар хэмжээ өмсдөг вэ?']], { emoji: '📏' }),
    w('试', 'shì', 'туршиж үзэх', 'Үйл үг', [['我可以试试吗？', 'Би туршиж үзэж болох уу?']], { emoji: '👕' }),
    w('贵', 'guì', 'үнэтэй', 'Тэмдэг нэр', [['这个包很贵。', 'Энэ цүнх үнэтэй.']], { ant: ['便宜'], emoji: '💵' }),
    w('便宜', 'pián yi', 'хямд', 'Тэмдэг нэр', [['这件衬衫很便宜。', 'Энэ цамц хямд.']], { ant: ['贵'], emoji: '👛' }),
    w('买', 'mǎi', 'худалдан авах', 'Үйл үг', [['我想买这个。', 'Би үүнийг авмаар байна.']], { ant: ['卖'], emoji: '🛍️' }),
    w('卖', 'mài', 'зарах', 'Үйл үг', [['他们卖电器。', 'Тэд цахилгаан бараа зардаг.']], { ant: ['买'], emoji: '🎁' }),
    w('钱', 'qián', 'мөнгө', 'Нэр үг', [['我没有钱。', 'Надад мөнгө байхгүй.']], { emoji: '💰' }),
  ],
  payment: [
    w('钱', 'qián', 'мөнгө', 'Нэр үг', [['我没有钱。', 'Надад мөнгө байхгүй.']], { emoji: '💰' }),
    w('付', 'fù', 'төлөх', 'Үйл үг', [['我怎么付钱？', 'Би яаж төлөх вэ?']], { emoji: '💳' }),
    w('银行', 'yín háng', 'банк', 'Нэр үг', [['银行开门了。', 'Банк нээлттэй.']], { emoji: '🏦' }),
  ],
  transport: [
    w('公共汽车', 'gōng gòng qì chē', 'автобус', 'Нэр үг', [['公共汽车晚了。', 'Автобус хоцорлоо.']], { emoji: '🚌' }),
    w('火车', 'huǒ chē', 'галт тэрэг', 'Нэр үг', [['火车很快。', 'Галт тэрэг хурдан.']], { emoji: '🚆' }),
    w('票', 'piào', 'тасалбар', 'Нэр үг', [['我要两张票。', 'Хоёр тасалбар авна.']], { emoji: '🎫' }),
    w('地铁', 'dì tiě', 'метро', 'Нэр үг', [['我坐地铁。', 'Би метрогоор явдаг.']], { emoji: '🚇' }),
    w('飞机', 'fēi jī', 'онгоц', 'Нэр үг', [['飞机起飞了。', 'Онгоц нисэв.']], { emoji: '✈️' }),
    w('站', 'zhàn', 'буудал', 'Нэр үг', [['车站在哪里？', 'Буудал хаана байна?']], { emoji: '🚉' }),
    w('自行车', 'zì xíng chē', 'дугуй', 'Нэр үг', [['我骑自行车。', 'Би дугуй унадаг.']], { emoji: '🚲' }),
  ],
  taxi: [
    w('出租车', 'chū zū chē', 'такси', 'Нэр үг', [['请叫出租车。', 'Такси дуудаач.']], { emoji: '🚕' }),
    w('司机', 'sī jī', 'жолооч', 'Нэр үг', [['司机很好。', 'Жолооч сайн хүн.']], { emoji: '🧑‍✈️' }),
    w('停', 'tíng', 'зогсох', 'Үйл үг', [['请在这里停。', 'Энд зогсооно уу.']], { emoji: '🛑' }),
  ],
  directions: [
    w('左', 'zuǒ', 'зүүн', 'Нэр үг', [['在这里左转。', 'Энд зүүн эргэ.']], { ant: ['右'], emoji: '⬅️' }),
    w('右', 'yòu', 'баруун', 'Нэр үг', [['往右走。', 'Баруун тийш яв.']], { ant: ['左'], emoji: '➡️' }),
    w('直走', 'zhí zǒu', 'чигээрээ явах', 'Үйл үг', [['一直走。', 'Чигээрээ яв.']], { emoji: '⬆️' }),
  ],
  hospital: [
    w('医生', 'yī shēng', 'эмч', 'Нэр үг', [['我需要医生。', 'Надад эмч хэрэгтэй.']], { emoji: '🧑‍⚕️' }),
    w('药', 'yào', 'эм', 'Нэр үг', [['吃这个药。', 'Энэ эмийг уу.']], { emoji: '💊' }),
    w('病', 'bìng', 'өвчин', 'Нэр үг', [['我生病了。', 'Би өвчтэй боллоо.']], { emoji: '🤒' }),
  ],
  pharmacy: [
    w('发烧', 'fā shāo', 'халуурах', 'Үйл үг', [['我发烧了。', 'Би халуурч байна.']], { emoji: '🌡️' }),
    w('咳嗽', 'ké sou', 'ханиалгах', 'Үйл үг', [['我咳嗽。', 'Би ханиаж байна.']], { emoji: '😷' }),
  ],
  work: [
    w('工作', 'gōng zuò', 'ажил', 'Нэр үг', [['我去工作。', 'Би ажилдаа явна.']], { emoji: '💼' }),
    w('办公室', 'bàn gōng shì', 'оффис', 'Нэр үг', [['办公室在市中心。', 'Оффис хотын төвд.']], { emoji: '🏢' }),
    w('会议', 'huì yì', 'хурал', 'Нэр үг', [['我们有会议。', 'Бид хуралтай.']], { emoji: '📅' }),
    w('老板', 'lǎo bǎn', 'дарга', 'Нэр үг', [['我的老板很好。', 'Миний дарга сайн.']], { emoji: '👔' }),
    w('同事', 'tóng shì', 'хамт ажиллагч', 'Нэр үг', [['他是我同事。', 'Тэр миний хамт ажиллагч.']], { emoji: '🤝' }),
    w('忙', 'máng', 'завгүй', 'Тэмдэг нэр', [['我很忙。', 'Би завгүй байна.']], { emoji: '😤' }),
    w('累', 'lèi', 'ядарсан', 'Тэмдэг нэр', [['我很累。', 'Би ядарсан.']], { emoji: '😫' }),
  ],
  school: [
    w('学校', 'xué xiào', 'сургууль', 'Нэр үг', [['我在学校学习。', 'Би сургуульд сурдаг.']], { emoji: '🏫' }),
    w('老师', 'lǎo shī', 'багш', 'Нэр үг', [['我们的老师很好。', 'Манай багш сайн.']], { ant: ['学生'], emoji: '🧑‍🏫' }),
    w('学生', 'xué sheng', 'оюутан', 'Нэр үг', [['他是好学生。', 'Тэр сайн оюутан.']], { ant: ['老师'], emoji: '🧑‍🎓' }),
    w('学习', 'xué xí', 'суралцах', 'Үйл үг', [['我想学习中文。', 'Би хятад хэл сурмаар байна.']], { emoji: '🧠' }),
  ],
  technology: [
    w('手机', 'shǒu jī', 'утас', 'Нэр үг', [['我的手机是新的。', 'Миний утас шинэ.']], { emoji: '📱' }),
    w('电脑', 'diàn nǎo', 'компьютер', 'Нэр үг', [['我在电脑上工作。', 'Компьютер дээр ажилладаг.']], { emoji: '💻' }),
    w('网络', 'wǎng luò', 'интернэт', 'Нэр үг', [['网络很慢。', 'Интернэт удаан.']], { emoji: '🌐' }),
  ],
  clothes: [
    w('衬衫', 'chèn shān', 'цамц', 'Нэр үг', [['这件衬衫是蓝色的。', 'Энэ цамц цэнхэр.']], { emoji: '👕' }),
    w('鞋', 'xié', 'гутал', 'Нэр үг', [['我的鞋是新的。', 'Миний гутал шинэ.']], { emoji: '👟' }),
    w('帽子', 'mào zi', 'малгай', 'Нэр үг', [['他戴帽子。', 'Тэр малгай өмссөн.']], { emoji: '🧢' }),
    w('裤子', 'kù zi', 'өмд', 'Нэр үг', [['这条裤子很贵。', 'Энэ өмд үнэтэй.']], { emoji: '👖' }),
    w('裙子', 'qún zi', 'банзал', 'Нэр үг', [['她穿裙子。', 'Тэр банзал өмссөн.']], { emoji: '👗' }),
    w('外套', 'wài tào', 'хүрэм', 'Нэр үг', [['穿上外套。', 'Хүрмээ өмс.']], { emoji: '🧥' }),
    w('穿', 'chuān', 'өмсөх', 'Үйл үг', [['我穿衣服。', 'Би хувцас өмсдөг.']], { emoji: '👕' }),
  ],
  weather: [
    w('天气', 'tiān qì', 'цаг агаар', 'Нэр үг', [['天气很好。', 'Цаг агаар сайхан.']], { emoji: '🌤️' }),
    w('雨', 'yǔ', 'бороо', 'Нэр үг', [['今天会下雨。', 'Өнөөдөр бороо орно.']], { emoji: '🌧️' }),
    w('热', 'rè', 'халуун', 'Тэмдэг нэр', [['今天很热。', 'Өнөөдөр халуун.']], { ant: ['冷'], emoji: '🔥' }),
    w('冷', 'lěng', 'хүйтэн', 'Тэмдэг нэр', [['很冷。', 'Хүйтэн байна.']], { ant: ['热'], emoji: '🥶' }),
    w('雪', 'xuě', 'цас', 'Нэр үг', [['下雪了。', 'Цас орж байна.']], { emoji: '❄️' }),
    w('风', 'fēng', 'салхи', 'Нэр үг', [['今天风很大。', 'Өнөөдөр салхи их.']], { emoji: '💨' }),
    w('晴天', 'qíng tiān', 'цэлмэг', 'Нэр үг', [['今天是晴天。', 'Өнөөдөр цэлмэг.']], { emoji: '☀️' }),
    w('阴天', 'yīn tiān', 'үүлэрхэг', 'Нэр үг', [['今天阴天。', 'Өнөөдөр үүлэрхэг.']], { emoji: '☁️' }),
  ],
  freetime: [
    w('音乐', 'yīn yuè', 'хөгжим', 'Нэр үг', [['我喜欢音乐。', 'Би хөгжимд дуртай.']], { emoji: '🎵' }),
    w('游戏', 'yóu xì', 'тоглоом', 'Нэр үг', [['我们玩游戏吧。', 'Тоглоом тоглоё.']], { emoji: '🎮' }),
    w('电影', 'diàn yǐng', 'кино', 'Нэр үг', [['我们看电影了。', 'Бид кино үзлээ.']], { emoji: '🎬' }),
  ],
  travel: [
    w('机场', 'jī chǎng', 'нисэх буудал', 'Нэр үг', [['机场很远。', 'Буудал хол.']], { emoji: '🛫' }),
    w('酒店', 'jiǔ diàn', 'зочид буудал', 'Нэр үг', [['我们的酒店很好。', 'Манай буудал сайхан.']], { emoji: '🏨' }),
    w('护照', 'hù zhào', 'пасспорт', 'Нэр үг', [['请出示护照。', 'Пасспортоо үзүүл.']], { emoji: '🛂' }),
    w('行李', 'xíng li', 'ачаа тээш', 'Нэр үг', [['我的行李很重。', 'Миний ачаа хүнд.']], { emoji: '🧳' }),
    w('地图', 'dì tú', 'газрын зураг', 'Нэр үг', [['给我一张地图。', 'Надад газрын зураг өг.']], { emoji: '🗺️' }),
    w('旅游', 'lǚ yóu', 'аялах', 'Үйл үг', [['我喜欢旅游。', 'Би аялах дуртай.']], { emoji: '🧳' }),
    w('相机', 'xiàng jī', 'камер', 'Нэр үг', [['带上相机。', 'Камераа авч яв.']], { emoji: '📷' }),
  ],
  emergency: [
    w('帮助', 'bāng zhù', 'тусламж', 'Нэр үг', [['请帮助我！', 'Туслаач!']], { emoji: '🆘' }),
    w('警察', 'jǐng chá', 'цагдаа', 'Нэр үг', [['叫警察！', 'Цагдаа дуудаарай!']], { emoji: '👮' }),
    w('火', 'huǒ', 'гал', 'Нэр үг', [['着火了！', 'Гал гарлаа!']], { emoji: '🔥' }),
  ],
};

const WORDS = { zh: ZH, en: EN, ja: {}, ko: {} };

const BULK = { zh: BULK_ZH, en: BULK_EN };

// getCourses is a pure function of `lang` over static module data — the result
// never changes at runtime, so cache it per language instead of rebuilding the
// whole catalog (now 700+ words across categories) on every call/render.
const _coursesCache = {};
export function getCourses(lang = 'zh') {
  if (_coursesCache[lang]) return _coursesCache[lang];
  const data = WORDS[lang] || {};
  const bulk = BULK[lang] || {};
  const result = CATEGORY_META.map(c => {
    const base = data[c.id] || [];
    const extraRaw = bulk[c.id] || [];
    const seen = new Set(base.map(w => w.target));
    const extra = extraRaw
      .filter(([t]) => !seen.has(t))
      .map(([t, r, m, ty]) => w(t, r, m, ty || 'Нэр үг', [], { emoji: '' }));
    return { ...c, words: [...base, ...extra] };
  });
  _coursesCache[lang] = result;
  return result;
}
export function findCategory(lang, id) { return getCourses(lang).find(c => c.id === id); }
export function findWord(lang, catId, wid) {
  const c = findCategory(lang, catId);
  return c ? c.words.find(x => x.id === wid) : null;
}
