// VOCA English Grammar (CEFR) curriculum

export const CEFR = [
  { level: 'A1', name: 'Эхлэгч', color: '#22C55E' },
  { level: 'A2', name: 'Суурь', color: '#38BDF8' },
  { level: 'B1', name: 'Дунд', color: '#A855F7' },
  { level: 'B2', name: 'Ахисан', color: '#F59E0B' },
  { level: 'C1', name: 'Гүнзгий', color: '#EF4444' },
];

function ex(arr) { return arr.map(([en, mn]) => ({ en, mn })); }

const LESSONS = [
  // ── A1 ──
  {
    id: 'present-simple', level: 'A1', title: 'Present Simple Tense', icon: 'Aa', time: '15–20 мин',
    desc: 'Одоогийн ердийн давтагддаг үйлдлийг илэрхийлдэг.',
    definition: 'Present Simple Tense нь одоо цагт байнга давтагддаг, ердийн үйлдлийг илэрхийлдэг.',
    useCases: [
      'Ердийн давтагддаг үйлдэл (every day, always, usually гэх мэт)',
      'Үнэн факт, ерөнхий үнэн',
      'Тогтмол хуваарь, хөтөлбөр',
      'Спортын тайлбар, өгүүлбэрийн ерөнхий үйлдэл',
    ],
    structure: [
      { form: 'I / You / We / They', pos: 'play football.', neg: "do not (don't) play football.", q: 'Do I / you / we / they play football?' },
      { form: 'He / She / It', pos: 'plays football.', neg: "does not (doesn't) play football.", q: 'Does he / she / it play football?' },
    ],
    note: 'He, She, It буюу 3-р ганц бие дээр үйл үг -s эсвэл -es дагавар авна.',
    examples: {
      Батлах: ex([['I play football every day.', 'Би өдөр бүр хөлбөмбөг тоглодог.'], ['She studies English.', 'Тэр англи хэл сурдаг.'], ['They live in London.', 'Тэд Лондонд амьдардаг.']]),
      Сөрөг: ex([["I don't play football.", 'Би хөлбөмбөг тоглодоггүй.'], ["She doesn't eat meat.", 'Тэр мах иддэггүй.']]),
      Асуух: ex([['Do you play football?', 'Чи хөлбөмбөг тоглодог уу?'], ['Does he study English?', 'Тэр англи хэл сурдаг уу?']]),
    },
    mistakes: [['He go to school.', 'He goes to school.', '3-р ганц бие дээр -es дагавар орно.'], ["She don't like it.", "She doesn't like it.", '3-р ганц бие дээр does ашиглана.']],
    practice: [
      { type: 'fill', q: 'He ___ to school every day.', options: ['go', 'goes', 'going'], answer: 1 },
      { type: 'fill', q: 'They ___ English.', options: ['studies', 'study', 'studys'], answer: 1 },
      { type: 'choice', q: '"Тэр кофе уудаг" гэдгийг сонго:', options: ['She drink coffee.', 'She drinks coffee.', 'She drinking coffee.'], answer: 1 },
    ],
    quiz: [
      { q: 'I ___ basketball on Sundays.', options: ['plays', 'play', 'playing'], answer: 1 },
      { q: 'She ___ in a bank.', options: ['work', 'works', 'working'], answer: 1 },
      { q: 'Negative: "He ___ like tea."', options: ["don't", "doesn't", 'not'], answer: 1 },
      { q: 'Question: "___ they live here?"', options: ['Do', 'Does', 'Is'], answer: 0 },
      { q: '"Ус 100°C-д буцалдаг" — ___', options: ['Water boil at 100°C.', 'Water boils at 100°C.', 'Water is boil at 100°C.'], answer: 1 },
    ],
    related: ['verb-to-be', 'question-forms', 'past-simple'],
  },
  {
    id: 'verb-to-be', level: 'A1', title: 'Verb To Be (am/is/are)', icon: 'Be', time: '10–15 мин',
    desc: '"байх" туслах үйл үг — am, is, are.',
    definition: 'To be (am/is/are) нь "байх" гэсэн утгатай, төлөв байдал, таних мэдээллийг илэрхийлнэ.',
    useCases: ['Хэн/юу болохыг хэлэх', 'Төлөв байдал, шинж чанар', 'Байршил'],
    structure: [
      { form: 'I', pos: 'am a student.', neg: "am not a student.", q: 'Am I a student?' },
      { form: 'He / She / It', pos: 'is happy.', neg: "is not (isn't) happy.", q: 'Is he / she / it happy?' },
      { form: 'You / We / They', pos: 'are friends.', neg: "are not (aren't) friends.", q: 'Are you / we / they friends?' },
    ],
    note: 'I → am, He/She/It → is, You/We/They → are.',
    examples: {
      Батлах: ex([['I am a teacher.', 'Би багш.'], ['She is tall.', 'Тэр өндөр.'], ['We are happy.', 'Бид баяртай байна.']]),
      Сөрөг: ex([["He isn't here.", 'Тэр энд байхгүй.'], ["They aren't ready.", 'Тэд бэлэн биш.']]),
      Асуух: ex([['Are you a student?', 'Чи оюутан уу?'], ['Is she your sister?', 'Тэр чиний эгч үү?']]),
    },
    mistakes: [['I is happy.', 'I am happy.', 'I дээр am ашиглана.'], ['They is here.', 'They are here.', 'They дээр are ашиглана.']],
    practice: [
      { type: 'fill', q: 'She ___ a doctor.', options: ['am', 'is', 'are'], answer: 1 },
      { type: 'fill', q: 'We ___ from Mongolia.', options: ['is', 'am', 'are'], answer: 2 },
    ],
    quiz: [
      { q: 'I ___ a student.', options: ['am', 'is', 'are'], answer: 0 },
      { q: 'He ___ my friend.', options: ['am', 'is', 'are'], answer: 1 },
      { q: 'They ___ happy.', options: ['is', 'am', 'are'], answer: 2 },
    ],
    related: ['present-simple', 'articles'],
  },
  {
    id: 'articles', level: 'A1', title: 'Articles (a / an / the)', icon: 'Th', time: '10–15 мин',
    desc: 'Тодорхой ба тодорхой бус артикль.',
    definition: 'a/an нь тодорхой бус (нэг), the нь тодорхой зүйлийг заана.',
    useCases: ['a/an — анх дурдаж буй нэг зүйл', 'the — аль хэдийн мэдэгдсэн зүйл', 'эгшгээр эхэлбэл an'],
    structure: [
      { form: 'a + гийгүүлэгч', pos: 'a book, a car', neg: '—', q: '—' },
      { form: 'an + эгшиг', pos: 'an apple, an hour', neg: '—', q: '—' },
      { form: 'the + тодорхой', pos: 'the sun, the book', neg: '—', q: '—' },
    ],
    note: 'Эгшгийн авиагаар эхэлбэл "an" (an apple). "the" нь хоёр талд мэдэгдэж буй зүйлд.',
    examples: {
      Батлах: ex([['I have a dog.', 'Надад нэг нохой бий.'], ['She ate an apple.', 'Тэр алим идсэн.'], ['The sun is bright.', 'Нар тод гэрэлтэж байна.']]),
      Сөрөг: ex([["It isn't a cat.", 'Энэ муур биш.']]),
      Асуух: ex([['Is this an egg?', 'Энэ өндөг үү?']]),
    },
    mistakes: [['I have a apple.', 'I have an apple.', 'Эгшгээр эхэлвэл an.'], ['Sun is hot.', 'The sun is hot.', 'Цор ганц зүйлд the.']],
    practice: [
      { type: 'fill', q: 'I saw ___ elephant.', options: ['a', 'an', 'the'], answer: 1 },
      { type: 'fill', q: '___ moon is beautiful.', options: ['A', 'An', 'The'], answer: 2 },
    ],
    quiz: [
      { q: 'She has ___ umbrella.', options: ['a', 'an', 'the'], answer: 1 },
      { q: 'He is ___ teacher.', options: ['a', 'an', 'the'], answer: 0 },
    ],
    related: ['plural-nouns', 'present-simple'],
  },
  {
    id: 'plural-nouns', level: 'A1', title: 'Plural Nouns', icon: 'Pl', time: '10 мин',
    desc: 'Нэр үгийн олон тоо.',
    definition: 'Олон тоог ихэвчлэн -s, заримдаа -es эсвэл онцгой хэлбэрээр үүсгэнэ.',
    useCases: ['Энгийн: + s (cat → cats)', '-s,-x,-ch,-sh: + es (box → boxes)', 'Онцгой: man → men, child → children'],
    structure: [
      { form: 'Энгийн', pos: 'book → books', neg: '—', q: '—' },
      { form: '-s/-x/-ch/-sh', pos: 'bus → buses', neg: '—', q: '—' },
      { form: 'Онцгой', pos: 'child → children', neg: '—', q: '—' },
    ],
    note: 'Зарим үг онцгой: man→men, woman→women, foot→feet, tooth→teeth.',
    examples: { Батлах: ex([['I have two cats.', 'Надад хоёр муур бий.'], ['There are three boxes.', 'Гурван хайрцаг байна.'], ['The children play.', 'Хүүхдүүд тоглож байна.']]) },
    mistakes: [['two childs', 'two children', 'Онцгой олон тоо.'], ['three boxs', 'three boxes', '-x дээр -es.']],
    practice: [{ type: 'fill', q: 'one box, two ___', options: ['boxs', 'boxes', 'box'], answer: 1 }],
    quiz: [{ q: 'one child, two ___', options: ['childs', 'childrens', 'children'], answer: 2 }, { q: 'one bus, two ___', options: ['buss', 'buses', 'busi'], answer: 1 }],
    related: ['articles'],
  },
  {
    id: 'question-forms', level: 'A1', title: 'Question Forms', icon: '?', time: '12 мин',
    desc: 'Асуултын өгүүлбэр зохиох.',
    definition: 'Yes/No асуултад do/does/is/are урд орно. Wh-асуултад what, where, when зэрэг орно.',
    useCases: ['Yes/No: Do you...?', 'Wh-: What do you...?', 'To be: Are you...?'],
    structure: [
      { form: 'Yes/No', pos: '—', neg: '—', q: 'Do you like tea?' },
      { form: 'Wh-', pos: '—', neg: '—', q: 'Where do you live?' },
      { form: 'To be', pos: '—', neg: '—', q: 'Are you happy?' },
    ],
    note: 'Үндсэн үйл үг асуултад үндсэн хэлбэрээрээ үлдэнэ (Does he go? — go, goes биш).',
    examples: { Асуух: ex([['Do you speak English?', 'Чи англиар ярьдаг уу?'], ['Where does she work?', 'Тэр хаана ажилладаг вэ?'], ['What is your name?', 'Чиний нэр хэн бэ?']]) },
    mistakes: [['Does he goes?', 'Does he go?', 'does-ийн дараа үндсэн хэлбэр.'], ['Where you live?', 'Where do you live?', 'do шаардлагатай.']],
    practice: [{ type: 'choice', q: 'Зөв асуултыг сонго:', options: ['Do she like it?', 'Does she like it?', 'Does she likes it?'], answer: 1 }],
    quiz: [{ q: '___ you speak Mongolian?', options: ['Do', 'Does', 'Are'], answer: 0 }, { q: '___ she live here?', options: ['Do', 'Does', 'Is'], answer: 1 }],
    related: ['present-simple', 'verb-to-be'],
  },

  // ── A2 ──
  {
    id: 'past-simple', level: 'A2', title: 'Past Simple Tense', icon: 'Pa', time: '15 мин',
    desc: 'Өнгөрсөн цагт дууссан үйлдэл.',
    definition: 'Past Simple нь өнгөрсөн цагт болж дууссан үйлдлийг илэрхийлнэ. Ердийн үйл үг -ed авна.',
    useCases: ['Өнгөрсөн дууссан үйлдэл (yesterday, last week)', 'Дараалсан үйл явдал', 'Түүх өгүүлэх'],
    structure: [
      { form: 'Бүх бие', pos: 'played football.', neg: "did not (didn't) play football.", q: 'Did you play football?' },
    ],
    note: 'Ердийн үйл үг + ed (play→played). Олон үг онцгой: go→went, eat→ate, see→saw.',
    examples: {
      Батлах: ex([['I played football yesterday.', 'Би өчигдөр хөлбөмбөг тоглосон.'], ['She went home.', 'Тэр гэртээ харьсан.']]),
      Сөрөг: ex([["I didn't see him.", 'Би түүнийг хараагүй.']]),
      Асуух: ex([['Did you eat lunch?', 'Чи өдрийн хоол идсэн үү?']]),
    },
    mistakes: [['I goed home.', 'I went home.', 'go онцгой: went.'], ["She didn't went.", "She didn't go.", "didn't-ийн дараа үндсэн хэлбэр."]],
    practice: [{ type: 'fill', q: 'I ___ to school yesterday.', options: ['go', 'went', 'goed'], answer: 1 }],
    quiz: [{ q: 'She ___ a book last night.', options: ['read', 'readed', 'reads'], answer: 0 }, { q: "He ___ come to the party.", options: ["didn't", "doesn't", "don't"], answer: 0 }],
    related: ['present-simple', 'present-perfect'],
  },
  {
    id: 'comparative', level: 'A2', title: 'Comparative & Superlative', icon: '>', time: '12 мин',
    desc: 'Харьцуулах зэрэг (-er, the -est).',
    definition: 'Хоёр зүйлийг харьцуулахад -er/more, хамгийн дээдийг the -est/the most ашиглана.',
    useCases: ['Богино тэмдэг: + er (tall→taller)', 'Урт тэмдэг: more (more beautiful)', 'Хамгийн: the -est / the most'],
    structure: [
      { form: 'Comparative', pos: 'taller than', neg: '—', q: '—' },
      { form: 'Superlative', pos: 'the tallest', neg: '—', q: '—' },
    ],
    note: 'Онцгой: good→better→best, bad→worse→worst.',
    examples: { Батлах: ex([['He is taller than me.', 'Тэр надаас өндөр.'], ['This is the best book.', 'Энэ хамгийн сайн ном.']]) },
    mistakes: [['more taller', 'taller', 'Давхар харьцуулалт болохгүй.'], ['the most tall', 'the tallest', 'Богино тэмдэг -est.']],
    practice: [{ type: 'fill', q: 'A car is ___ than a bike.', options: ['fast', 'faster', 'fastest'], answer: 1 }],
    quiz: [{ q: 'This is ___ book I have read.', options: ['good', 'better', 'the best'], answer: 2 }],
    related: ['present-simple'],
  },

  // ── B1 ──
  {
    id: 'present-perfect', level: 'B1', title: 'Present Perfect Tense', icon: 'Pf', time: '18 мин',
    desc: 'Өнгөрсөнд эхэлж одоог хүртэл үргэлжилсэн/үр дүнтэй холбоотой үйлдэл.',
    definition: 'Present Perfect (have/has + V3) нь өнгөрсөнд болсон боловч одоотой холбоотой үйлдлийг илэрхийлнэ.',
    useCases: ['Туршлага (I have been to Japan)', 'Саяхан дууссан үйлдэл (just, already)', 'Одоог хүртэл үргэлжилсэн (for, since)'],
    structure: [
      { form: 'I / You / We / They', pos: 'have finished.', neg: "have not (haven't) finished.", q: 'Have you finished?' },
      { form: 'He / She / It', pos: 'has finished.', neg: "has not (hasn't) finished.", q: 'Has he finished?' },
    ],
    note: 'have/has + үйл үгийн 3-р хэлбэр (V3): go→gone, eat→eaten, see→seen.',
    examples: {
      Батлах: ex([['I have finished my homework.', 'Би гэрийн даалгавраа дуусгасан.'], ['She has been to Paris.', 'Тэр Парист очиж байсан.']]),
      Сөрөг: ex([["I haven't seen him.", 'Би түүнийг хараагүй.']]),
      Асуух: ex([['Have you eaten?', 'Чи хооллочихсон уу?']]),
    },
    mistakes: [['I have went.', 'I have gone.', 'V3 хэлбэр: gone.'], ['She have finished.', 'She has finished.', '3-р ганц бие → has.']],
    practice: [{ type: 'fill', q: 'I have ___ my keys.', options: ['lose', 'lost', 'losed'], answer: 1 }],
    quiz: [{ q: 'She ___ already left.', options: ['have', 'has', 'is'], answer: 1 }, { q: 'I have ___ this movie.', options: ['see', 'saw', 'seen'], answer: 2 }],
    related: ['past-simple', 'passive-voice'],
  },
  {
    id: 'passive-voice', level: 'B1', title: 'Passive Voice', icon: 'Pv', time: '16 мин',
    desc: 'Үйлдлийг хүлээн авагч талаас илэрхийлэх.',
    definition: 'Passive (be + V3) нь хэн хийснээс илүү юу болсонд анхаарна.',
    useCases: ['Хийгч нь чухал биш үед', 'Албан ёсны/шинжлэх ухааны бичвэр'],
    structure: [
      { form: 'Present', pos: 'is made', neg: 'is not made', q: 'Is it made?' },
      { form: 'Past', pos: 'was made', neg: 'was not made', q: 'Was it made?' },
    ],
    note: 'be (am/is/are/was/were) + үйл үгийн 3-р хэлбэр (V3).',
    examples: { Батлах: ex([['This book was written in 2019.', 'Энэ ном 2019 онд бичигдсэн.'], ['English is spoken here.', 'Энд англиар ярьдаг.']]) },
    mistakes: [['The cake was make.', 'The cake was made.', 'V3 хэлбэр: made.']],
    practice: [{ type: 'fill', q: 'The house ___ built in 2000.', options: ['was', 'is', 'were'], answer: 0 }],
    quiz: [{ q: 'These cars ___ made in Japan.', options: ['is', 'are', 'was'], answer: 1 }],
    related: ['present-perfect'],
  },

  // ── A1 (нэмэлт) ──
  {
    id: 'this-that', level: 'A1', title: 'This / That / These / Those', icon: 'Td', time: '8 мин',
    desc: 'Зүйлийг заах төлөөний үг.',
    definition: 'this (ойр, ганц), that (хол, ганц), these (ойр, олон), those (хол, олон).',
    useCases: ['Ойр зүйл: this/these', 'Хол зүйл: that/those', 'Ганц/олон тоо ялгана'],
    structure: [{ form: 'Ганц', pos: 'this / that book', neg: '—', q: '—' }, { form: 'Олон', pos: 'these / those books', neg: '—', q: '—' }],
    note: 'this→these, that→those (олон тоонд).',
    examples: { Батлах: ex([['This is my book.', 'Энэ миний ном.'], ['Those are nice.', 'Тэдгээр нь сайхан.']]) },
    mistakes: [['this books', 'these books', 'Олон тоонд these.']],
    practice: [{ type: 'fill', q: '___ apples are fresh. (хол, олон)', options: ['This', 'These', 'Those'], answer: 2 }],
    quiz: [{ q: '___ is my pen. (ойр, ганц)', options: ['This', 'These', 'Those'], answer: 0 }],
    related: ['articles', 'plural-nouns'],
  },
  {
    id: 'possessive', level: 'A1', title: 'Possessive (my/your/his)', icon: 'My', time: '8 мин',
    desc: 'Эзэмшлийн төлөөний үг.',
    definition: 'my, your, his, her, its, our, their — хэний болохыг заана.',
    useCases: ['Эзэмшил заах', 'Нэр үгийн өмнө орно'],
    structure: [{ form: 'Subject → Possessive', pos: 'I → my, you → your, he → his, she → her, we → our, they → their', neg: '—', q: '—' }],
    note: 'Эзэмшлийн төлөөний үг нэр үгийн өмнө орно: my car, his book.',
    examples: { Батлах: ex([['This is my car.', 'Энэ миний машин.'], ['Her name is Sara.', 'Түүний нэр Сара.']]) },
    mistakes: [['This is me book.', 'This is my book.', 'me биш my.']],
    practice: [{ type: 'fill', q: 'She loves ___ dog.', options: ['she', 'her', 'hers'], answer: 1 }],
    quiz: [{ q: 'We like ___ school.', options: ['we', 'us', 'our'], answer: 2 }],
    related: ['verb-to-be'],
  },

  // ── A2 (нэмэлт) ──
  {
    id: 'future-will', level: 'A2', title: 'Future (will / be going to)', icon: 'Fu', time: '14 мин',
    desc: 'Ирээдүй цаг илэрхийлэх.',
    definition: 'will — шийдвэр/таамаг, be going to — төлөвлөсөн зүйл.',
    useCases: ['will — гэнэт шийдсэн, таамаг', 'be going to — урьдчилан төлөвлөсөн', 'Цаг агаарын таамаг'],
    structure: [{ form: 'will', pos: 'will go', neg: "won't go", q: 'Will you go?' }, { form: 'going to', pos: 'am going to go', neg: 'am not going to go', q: 'Are you going to go?' }],
    note: 'will + үндсэн үйл үг. be going to + үндсэн үйл үг.',
    examples: { Батлах: ex([['I will call you later.', 'Би чамруу дараа залгана.'], ['She is going to travel.', 'Тэр аялах гэж байна.']]), Сөрөг: ex([["I won't be late.", 'Би хоцрохгүй.']]) },
    mistakes: [['I will to go.', 'I will go.', "will-ийн дараа to байхгүй."]],
    practice: [{ type: 'fill', q: 'I think it ___ rain.', options: ['will', 'is going', 'go'], answer: 0 }],
    quiz: [{ q: 'They ___ visit us tomorrow.', options: ['will', 'wills', 'are will'], answer: 0 }, { q: 'Negative: "He ___ come."', options: ["won't", "willn't", "not will"], answer: 0 }],
    related: ['present-simple', 'past-simple'],
  },
  {
    id: 'frequency', level: 'A2', title: 'Adverbs of Frequency', icon: 'Af', time: '10 мин',
    desc: 'Давтамжийн дайвар үг.',
    definition: 'always, usually, often, sometimes, never — давтамжийг заана.',
    useCases: ['Давтамж заах', 'Үндсэн үйл үгийн өмнө, be-ийн дараа'],
    structure: [{ form: 'Байрлал', pos: 'I always study. / She is always happy.', neg: '—', q: '—' }],
    note: 'Давтамжийн дайвар үндсэн үйл үгийн ӨМНӨ, харин be (am/is/are)-ийн ДАРАА орно.',
    examples: { Батлах: ex([['I always drink coffee.', 'Би үргэлж кофе уудаг.'], ['He is never late.', 'Тэр хэзээ ч хоцордоггүй.']]) },
    mistakes: [['I drink always coffee.', 'I always drink coffee.', 'Дайвар үйл үгийн өмнө.']],
    practice: [{ type: 'choice', q: 'Зөв байрлалыг сонго:', options: ['She goes usually home.', 'She usually goes home.', 'Usually she goes home usually.'], answer: 1 }],
    quiz: [{ q: 'I ___ eat breakfast.', options: ['always', 'am always', 'always am'], answer: 0 }],
    related: ['present-simple'],
  },
  {
    id: 'modals', level: 'A2', title: 'Modals (can / must / should)', icon: 'Mo', time: '12 мин',
    desc: 'Чадвар, үүрэг, зөвлөгөө илэрхийлэх туслах үйл үг.',
    definition: 'can (чадвар), must (заавал), should (зөвлөгөө). Дараа нь үндсэн үйл үг орно.',
    useCases: ['can — чадвар/боломж', 'must — заавал', 'should — зөвлөгөө'],
    structure: [{ form: 'Бүх бие', pos: 'can / must / should go', neg: "cannot / must not / should not go", q: 'Can / Should you go?' }],
    note: 'Модал үйл үгийн дараа to байхгүй, үндсэн хэлбэр орно: can swim (can to swim биш).',
    examples: { Батлах: ex([['I can swim.', 'Би усанд сэлж чадна.'], ['You should rest.', 'Чи амрах хэрэгтэй.'], ['We must go now.', 'Бид одоо явах ёстой.']]) },
    mistakes: [['I can to swim.', 'I can swim.', 'Модалын дараа to байхгүй.'], ['She musts go.', 'She must go.', 'Модал -s авдаггүй.']],
    practice: [{ type: 'fill', q: 'You ___ see a doctor.', options: ['should', 'shoulds', 'to should'], answer: 0 }],
    quiz: [{ q: 'He ___ speak three languages.', options: ['can', 'cans', 'can to'], answer: 0 }, { q: 'You ___ smoke here.', options: ["must not", "not must", "musts not"], answer: 0 }],
    related: ['present-simple'],
  },

  // ── B1 (нэмэлт) ──
  {
    id: 'first-conditional', level: 'B1', title: 'First Conditional', icon: 'C1', time: '14 мин',
    desc: 'Бодит ирээдүйн нөхцөл (If + present, will).',
    definition: 'If + Present Simple, ... will + үйл үг. Бодитой болж болзошгүй нөхцөл.',
    useCases: ['Ирээдүйд болж болзошгүй нөхцөл', 'Анхааруулга, амлалт'],
    structure: [{ form: 'If-хэсэг', pos: 'If it rains,', neg: '—', q: '—' }, { form: 'Үндсэн хэсэг', pos: 'I will stay home.', neg: "I won't go out.", q: '—' }],
    note: 'If-хэсэгт ирээдүйд ч гэсэн Present Simple ашиглана (If it will rain биш).',
    examples: { Батлах: ex([['If you study, you will pass.', 'Хичээллэвэл чи тэнцэнэ.'], ['If it rains, we will stay.', 'Бороо орвол бид үлдэнэ.']]) },
    mistakes: [['If it will rain, ...', 'If it rains, ...', 'If-хэсэгт Present Simple.']],
    practice: [{ type: 'fill', q: 'If you ___ hard, you will succeed.', options: ['will work', 'work', 'works'], answer: 1 }],
    quiz: [{ q: 'If it ___ sunny, we will go.', options: ['is', 'will be', 'be'], answer: 0 }, { q: 'I ___ help if you ask.', options: ['will', 'would', 'am'], answer: 0 }],
    related: ['present-simple', 'future-will'],
  },
  {
    id: 'gerund-infinitive', level: 'B1', title: 'Gerund & Infinitive', icon: 'Gi', time: '14 мин',
    desc: 'Үйл үг + -ing эсвэл to + үйл үг.',
    definition: 'Зарим үйл үгийн дараа gerund (-ing), зарим дараа infinitive (to + V) орно.',
    useCases: ['enjoy/like + V-ing', 'want/decide + to V', 'Захирагдах үйл үгээс хамаарна'],
    structure: [{ form: 'Gerund', pos: 'enjoy reading', neg: '—', q: '—' }, { form: 'Infinitive', pos: 'want to read', neg: '—', q: '—' }],
    note: 'enjoy, finish, avoid → -ing. want, decide, hope → to + V.',
    examples: { Батлах: ex([['I enjoy swimming.', 'Би усанд сэлэх дуртай.'], ['She wants to learn.', 'Тэр сурахыг хүсэж байна.']]) },
    mistakes: [['I enjoy to swim.', 'I enjoy swimming.', 'enjoy + V-ing.'], ['I want learning.', 'I want to learn.', 'want + to V.']],
    practice: [{ type: 'fill', q: 'I finished ___ my homework.', options: ['to do', 'doing', 'do'], answer: 1 }],
    quiz: [{ q: 'She decided ___ a doctor.', options: ['becoming', 'to become', 'become'], answer: 1 }],
    related: ['present-simple'],
  },

  // ── B2 ──
  {
    id: 'second-conditional', level: 'B2', title: 'Second Conditional', icon: 'C2', time: '15 мин',
    desc: 'Төсөөллийн/бодит бус нөхцөл (If + past, would).',
    definition: 'If + Past Simple, ... would + үйл үг. Одоо/ирээдүйн бодит бус, төсөөллийн нөхцөл.',
    useCases: ['Бодит бус, төсөөллийн нөхцөл', 'Зөвлөгөө (If I were you...)'],
    structure: [{ form: 'If-хэсэг', pos: 'If I had money,', neg: '—', q: '—' }, { form: 'Үндсэн', pos: 'I would travel.', neg: "I wouldn't worry.", q: '—' }],
    note: 'If-хэсэгт бүх биед "were" хэрэглэж болно: If I were you.',
    examples: { Батлах: ex([['If I were rich, I would help.', 'Хэрэв би баян байсан бол тусална.'], ['If I had time, I would read.', 'Цагтай байсан бол би уншина.']]) },
    mistakes: [['If I was you...', 'If I were you...', 'Албан ёсоор were.'], ['If I had money, I will...', 'If I had money, I would...', 'would ашиглана.']],
    practice: [{ type: 'fill', q: 'If I ___ you, I would apologize.', options: ['am', 'were', 'will be'], answer: 1 }],
    quiz: [{ q: 'If she had a car, she ___ drive.', options: ['will', 'would', 'is'], answer: 1 }],
    related: ['first-conditional'],
  },
  {
    id: 'relative-clauses', level: 'B2', title: 'Relative Clauses', icon: 'Rc', time: '15 мин',
    desc: 'who, which, that-ээр өгүүлбэр холбох.',
    definition: 'who (хүн), which (юм), that (хоёул), where (газар) — нэр үгийг тодотгох гишүүн өгүүлбэр.',
    useCases: ['Нэр үгийг тодорхойлох', 'Хоёр өгүүлбэрийг нэгтгэх'],
    structure: [{ form: 'who/that (хүн)', pos: 'The man who called...', neg: '—', q: '—' }, { form: 'which/that (юм)', pos: 'The book which I read...', neg: '—', q: '—' }],
    note: 'who → хүн, which → юм, that → хоёул, where → газар.',
    examples: { Батлах: ex([['The girl who sings is my sister.', 'Дуулж буй охин миний эгч.'], ['This is the house where I live.', 'Энэ миний амьдардаг байшин.']]) },
    mistakes: [['The man which called...', 'The man who called...', 'Хүнд who.']],
    practice: [{ type: 'fill', q: 'The car ___ I bought is red.', options: ['who', 'which', 'where'], answer: 1 }],
    quiz: [{ q: 'A doctor is a person ___ helps sick people.', options: ['which', 'who', 'where'], answer: 1 }],
    related: ['present-simple'],
  },

  // ── C1 ──
  {
    id: 'inversion', level: 'C1', title: 'Inversion', icon: 'In', time: '16 мин',
    desc: 'Онцлох/албан ёсны урвуу бүтэц.',
    definition: 'Сөрөг утгатай дайвар үг өгүүлбэрийн эхэнд орвол subject-auxiliary урвана (Never have I...).',
    useCases: ['Онцлох, албан ёсны хэв маяг', 'Never, Rarely, Hardly зэргээр эхлэх'],
    structure: [{ form: 'Энгийн', pos: 'I have never seen this.', neg: '—', q: '—' }, { form: 'Inversion', pos: 'Never have I seen this.', neg: '—', q: '—' }],
    note: 'Never, Rarely, Seldom, Hardly, Not only... эхэнд орвол туслах үйл үг subject-ийн өмнө орно.',
    examples: { Батлах: ex([['Never have I been so happy.', 'Би хэзээ ч ийм баяртай байгаагүй.'], ['Rarely does he complain.', 'Тэр ховорхон гомдоллодог.']]) },
    mistakes: [['Never I have seen...', 'Never have I seen...', 'Туслах үйл үг subject-ийн өмнө.']],
    practice: [{ type: 'choice', q: 'Зөв inversion-ийг сонго:', options: ['Never I will forget.', 'Never will I forget.', 'Never forget I will.'], answer: 1 }],
    quiz: [{ q: '"Hardly ___ he arrived when it started."', options: ['has', 'had', 'have'], answer: 1 }],
    related: ['present-perfect'],
  },

  // ── A1 (Essential Grammar in Use) ──
  {
    id: 'present-continuous', book: 'essential-grammar-in-use', level: 'A1', title: 'Present Continuous (I am doing)', icon: 'Ci', time: '15 мин',
    desc: 'Яг одоо болж буй үйлдлийг илэрхийлдэг.',
    definition: 'Present Continuous (am/is/are + V-ing) нь яг ярьж буй мөчид болж буй үйлдэл, эсвэл ойрын ирээдүйн товлосон төлөвлөгөөг илэрхийлнэ.',
    useCases: ['Яг одоо болж буй үйлдэл (now, at the moment)', 'Түр зуурын нөхцөл байдал', 'Ойрын ирээдүйн товлосон төлөвлөгөө'],
    structure: [
      { form: 'I', pos: 'am doing.', neg: 'am not doing.', q: 'Am I doing?' },
      { form: 'He / She / It', pos: 'is doing.', neg: "is not (isn't) doing.", q: 'Is he / she / it doing?' },
      { form: 'You / We / They', pos: 'are doing.', neg: "are not (aren't) doing.", q: 'Are you / we / they doing?' },
    ],
    note: 'be (am/is/are) + үйл үг-ing. Present Simple-ээс ялгаа: Continuous нь ЯГ ОДОО, Simple нь ЕРДИЙН давтагддаг үйлдэл.',
    examples: {
      Батлах: ex([['I am reading a book now.', 'Би одоо ном уншиж байна.'], ['She is cooking dinner.', 'Тэр оройн хоол хийж байна.'], ['They are watching TV.', 'Тэд зурагт үзэж байна.']]),
      Сөрөг: ex([["He isn't listening.", 'Тэр сонсохгүй байна.']]),
      Асуух: ex([['What are you doing?', 'Чи юу хийж байна вэ?'], ['Is it raining?', 'Бороо орж байна уу?']]),
    },
    mistakes: [['I am reading books every day.', 'I read books every day.', 'Давтагддаг үйлдэлд Present Simple.'], ['She is knowing the answer.', 'She knows the answer.', 'know мэдрэхүйн үйл үг тул Continuous авдаггүй.']],
    practice: [
      { type: 'fill', q: 'Listen! She ___ (sing).', options: ['sings', 'is singing', 'sing'], answer: 1 },
      { type: 'fill', q: 'Right now, I ___ my homework.', options: ['do', 'am doing', 'did'], answer: 1 },
    ],
    quiz: [
      { q: 'Look! It ___ snow.', options: ['snows', 'is snowing', 'snow'], answer: 1 },
      { q: 'They ___ football at the moment.', options: ['play', 'plays', 'are playing'], answer: 2 },
    ],
    related: ['present-simple', 'verb-to-be'],
  },
  {
    id: 'have-got', book: 'essential-grammar-in-use', level: 'A1', title: 'Have / Have got', icon: 'Hg', time: '10 мин',
    desc: 'Эзэмшил илэрхийлэх have болон have got.',
    definition: 'have (has) болон have got (has got) хоёулаа "байх, эзэмших" гэсэн ижил утгатай, ярианы хэлэнд have got илүү түгээмэл.',
    useCases: ['Эд зүйл эзэмших', 'Гэр бүл, харилцаа', 'Шинж чанар (have got blue eyes)'],
    structure: [
      { form: 'I / You / We / They', pos: 'have (got) a car.', neg: "don't have / haven't got a car.", q: 'Do you have / Have you got a car?' },
      { form: 'He / She / It', pos: 'has (got) a car.', neg: "doesn't have / hasn't got a car.", q: 'Does he have / Has he got a car?' },
    ],
    note: 'have got хэлбэрт "do/does" биш "have/has" өөрөө туслах үйл үг болно: Have you got...? (Do you have got биш).',
    examples: {
      Батлах: ex([['I have a sister.', 'Надад эгч бий.'], ['She has got two dogs.', 'Түүнд хоёр нохой бий.']]),
      Сөрөг: ex([["I haven't got a car.", 'Надад машин байхгүй.']]),
      Асуух: ex([['Have you got a pen?', 'Чамд үзэг бий юу?'], ['Does she have a laptop?', 'Түүнд лаптоп бий юу?']]),
    },
    mistakes: [['Do you have got a car?', 'Have you got a car? / Do you have a car?', 'Хоёр хэлбэрийг холихгүй.'], ['She have got a cat.', 'She has got a cat.', '3-р ганц бие → has.']],
    practice: [{ type: 'fill', q: '___ you got a bicycle?', options: ['Do', 'Have', 'Are'], answer: 1 }],
    quiz: [
      { q: 'He ___ got a new phone.', options: ['have', 'has', 'is'], answer: 1 },
      { q: 'I ___ have any money.', options: ["don't", "doesn't", 'not'], answer: 0 },
    ],
    related: ['present-simple', 'possessive'],
  },
  {
    id: 'there-is-are', book: 'essential-grammar-in-use', level: 'A1', title: 'There is / There are', icon: 'Ti', time: '10 мин',
    desc: 'Ямар нэг зүйл байгааг мэдэгдэх.',
    definition: 'There is/are нь тухайн газарт ямар нэг зүйл байгаа эсэхийг мэдэгдэнэ. Ганцад there is, олонд there are.',
    useCases: ['Байгаа зүйлийг дурдах', 'Тоо ярих (there are three books)', 'Тодорхойгүй зүйл дурдах'],
    structure: [
      { form: 'Ганц', pos: 'There is a book on the table.', neg: "There isn't a book.", q: 'Is there a book?' },
      { form: 'Олон', pos: 'There are two books.', neg: "There aren't any books.", q: 'Are there any books?' },
    ],
    note: "There is/There's (ганц), There are (олон). Асуултад any ихэвчлэн ашиглана: Are there any...?",
    examples: {
      Батлах: ex([['There is a cat in the garden.', 'Цэцэрлэгт муур байна.'], ['There are five students in the room.', 'Өрөөнд таван оюутан байна.']]),
      Сөрөг: ex([["There isn't any milk.", 'Сүү байхгүй байна.']]),
      Асуух: ex([['Is there a bank near here?', 'Ойролцоо банк байгаа юу?'], ['Are there any shops?', 'Дэлгүүр байгаа юу?']]),
    },
    mistakes: [['It is a book on the table.', 'There is a book on the table.', 'Байгааг мэдэгдэхэд There is.'], ['There is three cats.', 'There are three cats.', 'Олон тоонд There are.']],
    practice: [{ type: 'fill', q: '___ a problem with my computer.', options: ['There is', 'There are', 'It is'], answer: 0 }],
    quiz: [
      { q: '___ any eggs in the fridge?', options: ['Is there', 'Are there', 'Is it'], answer: 1 },
      { q: 'There ___ 30 students in our class.', options: ['is', 'are', 'be'], answer: 1 },
    ],
    related: ['plural-nouns', 'some-any'],
  },
  {
    id: 'some-any', book: 'essential-grammar-in-use', level: 'A1', title: 'Some / Any / No', icon: 'Sa', time: '10 мин',
    desc: 'Тодорхойгүй тоо хэмжээ илэрхийлэх.',
    definition: 'some нь батлах өгүүлбэрт, any нь сөрөг ба асуух өгүүлбэрт, no нь "огт байхгүй" гэсэн утгаар ашиглагдана.',
    useCases: ['some — батлах (I have some money)', "any — сөрөг/асуух (I don't have any money)", 'no — байхгүй байдлыг онцлох'],
    structure: [
      { form: 'Батлах', pos: 'I have some apples.', neg: '—', q: '—' },
      { form: 'Сөрөг', pos: '—', neg: "I don't have any apples.", q: '—' },
      { form: 'Асуух', pos: '—', neg: '—', q: 'Do you have any apples?' },
    ],
    note: "Санал болгох/хүсэх асуултад some ашиглаж болно: Would you like some tea? no = not any (илүү хүчтэй): There is no milk. = There isn't any milk.",
    examples: {
      Батлах: ex([['There is some water in the bottle.', 'Лонхонд бага зэрэг ус бий.'], ['I need some help.', 'Надад тусламж хэрэгтэй.']]),
      Сөрөг: ex([["I don't have any brothers.", 'Надад ах дүү байхгүй.']]),
      Асуух: ex([['Is there any sugar?', 'Элсэн чихэр байгаа юу?'], ['Would you like some coffee?', 'Кофе уухыг хүсэж байна уу?']]),
    },
    mistakes: [['I have some no money.', "I have no money. / I don't have any money.", 'no, any хоёрыг хамт хэрэглэхгүй.'], ['Do you have some time?', 'Do you have any time?', 'Энгийн асуултад any.']],
    practice: [{ type: 'fill', q: "I don't have ___ questions.", options: ['some', 'any', 'no'], answer: 1 }],
    quiz: [
      { q: 'There are ___ nice restaurants here.', options: ['some', 'any', 'no'], answer: 0 },
      { q: 'We have ___ time left.', options: ['some', 'no', 'any'], answer: 1 },
    ],
    related: ['there-is-are', 'plural-nouns'],
  },
  {
    id: 'object-pronouns', book: 'essential-grammar-in-use', level: 'A1', title: 'Object Pronouns (me/him/them)', icon: 'Op', time: '8 мин',
    desc: 'Үйл үгийн дараа орох төлөөний үг.',
    definition: 'me, you, him, her, it, us, them — үйл үг эсвэл предлогийн дараа орох төлөөний үг.',
    useCases: ['Үйл үгийн дараа (I love her)', 'Предлогийн дараа (with him)'],
    structure: [
      { form: 'I → me', pos: 'She loves me.', neg: '—', q: '—' },
      { form: 'He → him', pos: 'I saw him.', neg: '—', q: '—' },
      { form: 'They → them', pos: 'Give it to them.', neg: '—', q: '—' },
    ],
    note: 'Subject: I, you, he, she, it, we, they → Object: me, you, him, her, it, us, them.',
    examples: { Батлах: ex([['Can you help me?', 'Чи надад тусалж чадах уу?'], ['I know her very well.', 'Би түүнийг сайн мэднэ.']]) },
    mistakes: [['I love she.', 'I love her.', 'Үйл үгийн дараа object хэлбэр.'], ['Give it to I.', 'Give it to me.', 'Предлогийн дараа object хэлбэр.']],
    practice: [{ type: 'fill', q: 'Can you give ___ your pen? (I)', options: ['I', 'me', 'my'], answer: 1 }],
    quiz: [
      { q: 'She called ___ yesterday. (he)', options: ['he', 'him', 'his'], answer: 1 },
      { q: 'We saw ___ at the party. (they)', options: ['they', 'them', 'their'], answer: 1 },
    ],
    related: ['possessive', 'verb-to-be'],
  },
  {
    id: 'prepositions-time', book: 'essential-grammar-in-use', level: 'A1', title: 'Prepositions of Time (at/on/in)', icon: 'Pt', time: '10 мин',
    desc: 'Цаг хугацаа заах предлог.',
    definition: 'at цаг заана, on өдөр/огноо заана, in сар/жил/улирал заана.',
    useCases: ['at — тодорхой цаг (at 8 o\'clock)', 'on — өдөр, огноо (on Monday)', 'in — сар, жил, улирал (in July)'],
    structure: [
      { form: 'at', pos: "at 8 o'clock, at night, at the weekend", neg: '—', q: '—' },
      { form: 'on', pos: 'on Monday, on 1st May', neg: '—', q: '—' },
      { form: 'in', pos: 'in July, in 2025, in winter', neg: '—', q: '—' },
    ],
    note: 'Онцгой: at night, харин in the morning/afternoon/evening.',
    examples: { Батлах: ex([["I wake up at 7 o'clock.", 'Би 7 цагт сэрдэг.'], ['We meet on Sundays.', 'Бид ням гарагт уулздаг.'], ['She was born in 2001.', 'Тэр 2001 онд төрсөн.']]) },
    mistakes: [["on 7 o'clock", "at 7 o'clock", 'Тодорхой цагт at.'], ['in Monday', 'on Monday', 'Өдөрт on.']],
    practice: [{ type: 'fill', q: 'My birthday is ___ June.', options: ['at', 'on', 'in'], answer: 2 }],
    quiz: [
      { q: 'The shop opens ___ 9 a.m.', options: ['at', 'on', 'in'], answer: 0 },
      { q: 'See you ___ Friday!', options: ['at', 'on', 'in'], answer: 1 },
    ],
    related: ['prepositions-place'],
  },
  {
    id: 'prepositions-place', book: 'essential-grammar-in-use', level: 'A1', title: 'Prepositions of Place', icon: 'Pp', time: '10 мин',
    desc: 'Байршил заах предлог: in front of, behind, next to.',
    definition: 'in, on, at, next to, in front of, behind, between, under, above — зүйлийн байршлыг заана.',
    useCases: ['in — дотор (in the box)', 'on — гадаргуу дээр (on the table)', 'at — цэг (at the door)', 'in front of / behind / next to / between — харьцангуй байрлал'],
    structure: [
      { form: 'in', pos: 'in the bag', neg: '—', q: '—' },
      { form: 'on', pos: 'on the desk', neg: '—', q: '—' },
      { form: 'next to', pos: 'next to the window', neg: '—', q: '—' },
    ],
    note: 'in front of ↔ behind (эсрэг утга). between = хоёрын хооронд, among = олны дунд.',
    examples: { Батлах: ex([['The cat is under the table.', 'Муур ширээний доор байна.'], ['The bank is next to the shop.', 'Банк дэлгүүрийн хажууд байна.'], ['She is standing between us.', 'Тэр бидний хооронд зогсож байна.']]) },
    mistakes: [['in front the house', 'in front of the house', 'in front of гурван үгтэй.']],
    practice: [{ type: 'fill', q: 'The book is ___ the table. (гадаргуу дээр)', options: ['in', 'on', 'at'], answer: 1 }],
    quiz: [
      { q: 'The park is ___ the school and the hospital.', options: ['between', 'among', 'next'], answer: 0 },
      { q: 'He is standing ___ the door.', options: ['in front of', 'in front', 'front of'], answer: 0 },
    ],
    related: ['prepositions-time'],
  },

  // ── A2 (Essential Grammar in Use) ──
  {
    id: 'past-continuous', book: 'essential-grammar-in-use', level: 'A2', title: 'Past Continuous (I was doing)', icon: 'Pc', time: '14 мин',
    desc: 'Өнгөрсөнд яг тодорхой мөчид үргэлжилж байсан үйлдэл.',
    definition: 'Past Continuous (was/were + V-ing) нь өнгөрсөн цагийн тодорхой мөчид явагдаж байсан үйлдлийг илэрхийлнэ, ихэвчлэн Past Simple-тэй хамт таслах явдал өгүүлэхэд ашиглана.',
    useCases: ['Өнгөрсний тодорхой цэгт үргэлжилж байсан үйлдэл (at 8pm I was sleeping)', 'Урт үйлдлийн явцад богино үйлдэл тохиолдох (when/while)', 'Түүхийн дэвсгэр өгүүлэх'],
    structure: [
      { form: 'I / He / She / It', pos: 'was doing.', neg: "was not (wasn't) doing.", q: 'Was I / he / she / it doing?' },
      { form: 'You / We / They', pos: 'were doing.', neg: "were not (weren't) doing.", q: 'Were you / we / they doing?' },
    ],
    note: 'when + Past Simple (богино үйлдэл тасалсан), while + Past Continuous (урт үйлдэл).',
    examples: {
      Батлах: ex([['I was watching TV at 9pm.', 'Би 9 цагт зурагт үзэж байсан.'], ['They were playing when it started to rain.', 'Бороо орж эхлэхэд тэд тоглож байсан.']]),
      Сөрөг: ex([["She wasn't listening.", 'Тэр сонсоогүй байсан.']]),
      Асуух: ex([['What were you doing at midnight?', 'Шөнө дунд чи юу хийж байсан бэ?']]),
    },
    mistakes: [['While I was walk...', 'While I was walking...', 'Continuous-д -ing шаардлагатай.'], ['I was knowing him.', 'I knew him.', 'know Continuous авдаггүй үйл үг.']],
    practice: [{ type: 'fill', q: 'I ___ (sleep) when the phone rang.', options: ['slept', 'was sleeping', 'sleep'], answer: 1 }],
    quiz: [
      { q: 'While she ___ dinner, he watched TV.', options: ['cooked', 'was cooking', 'cooks'], answer: 1 },
      { q: 'They ___ football at 5pm yesterday.', options: ['played', 'were playing', 'play'], answer: 1 },
    ],
    related: ['past-simple', 'present-continuous'],
  },
  {
    id: 'used-to', book: 'essential-grammar-in-use', level: 'A2', title: 'Used to', icon: 'Ut', time: '10 мин',
    desc: 'Өмнө нь байсан боловч одоо болдоггүй зуршил, төлөв.',
    definition: 'used to + үндсэн үйл үг нь өнгөрсөнд байнга болдог байсан ч одоо болдоггүй зуршил/төлөв байдлыг илэрхийлнэ.',
    useCases: ['Өнгөрсний зуршил (I used to smoke)', 'Өнгөрсний төлөв байдал (There used to be a park here)'],
    structure: [{ form: 'Бүх бие', pos: 'used to play.', neg: "didn't use to play.", q: 'Did you use to play?' }],
    note: 'used to нь зөвхөн ӨНГӨРСӨНД хэрэглэгдэнэ, одоо цагт байхгүй ("I use to" гэж хэлдэггүй).',
    examples: {
      Батлах: ex([['I used to live in London.', 'Би урьд Лондонд амьдардаг байсан.'], ['She used to play the piano.', 'Тэр урьд төгөлдөр хуур тоглодог байсан.']]),
      Сөрөг: ex([["He didn't use to like coffee.", 'Тэр урьд кофег дургүй байсан.']]),
      Асуух: ex([['Did you use to play football?', 'Чи урьд хөлбөмбөг тоглодог байсан уу?']]),
    },
    mistakes: [['I use to smoke.', 'I used to smoke.', 'used to хэлбэрт үргэлж -d.'], ['I am used to living here.', '(be used to = дасах, used to = зуршил — хоёр өөр бүтэц)', 'Бүтцийг бүү хольж хэрэглэ.']],
    practice: [{ type: 'fill', q: 'When I was young, I ___ play outside every day.', options: ['use to', 'used to', 'was used to'], answer: 1 }],
    quiz: [
      { q: 'She ___ have long hair.', options: ['use to', 'used to', 'using to'], answer: 1 },
      { q: '___ you use to live here?', options: ['Did', 'Were', 'Do'], answer: 0 },
    ],
    related: ['past-simple', 'past-continuous'],
  },
  {
    id: 'countable-uncountable', book: 'essential-grammar-in-use', level: 'A2', title: 'Countable & Uncountable Nouns', icon: 'Cu', time: '12 мин',
    desc: 'Тоологдох ба тоологддоггүй нэр үг.',
    definition: 'Countable нь тоологдох нэр үг (a book, two books), uncountable нь тоологддоггүй, ганцаараа ашиглагдана (water, information, money).',
    useCases: ['Countable: a/an, олон тоо -s авна', 'Uncountable: a/an авахгүй, олон тоо болдоггүй', 'much (uncountable), many (countable) хэрэглэнэ'],
    structure: [
      { form: 'Countable', pos: 'a book / books', neg: '—', q: '—' },
      { form: 'Uncountable', pos: 'water / some water', neg: '—', q: '—' },
    ],
    note: 'Түгээмэл uncountable: money, information, advice, furniture, news, water, rice. Хэмжих үед a piece of, a bottle of, a cup of зэрэг хэрэглэнэ.',
    examples: { Батлах: ex([['I need some information.', 'Надад бага мэдээлэл хэрэгтэй.'], ['She has three books.', 'Түүнд гурван ном бий.'], ['Can I have a glass of water?', 'Надад нэг аяга ус өгөх үү?']]) },
    mistakes: [['I need an information.', 'I need some information.', 'information uncountable, an авахгүй.'], ['many money', 'much money', 'money uncountable → much.']],
    practice: [{ type: 'fill', q: 'How ___ money do you have?', options: ['many', 'much', 'a lot'], answer: 1 }],
    quiz: [
      { q: 'She gave me some good ___.', options: ['advices', 'advice', 'an advice'], answer: 1 },
      { q: 'How ___ books did you buy?', options: ['much', 'many', 'a lot of'], answer: 1 },
    ],
    related: ['much-many', 'plural-nouns'],
  },
  {
    id: 'much-many', book: 'essential-grammar-in-use', level: 'A2', title: 'Much / Many / A lot of / A few / A little', icon: 'Mm', time: '10 мин',
    desc: 'Хэмжээ, тоо илэрхийлэх үгс.',
    definition: 'many + countable, much + uncountable, a lot of хоёуланд, a few + countable (цөөн), a little + uncountable (бага).',
    useCases: ['many books, much time', 'a lot of — албан бус, батлах өгүүлбэрт түгээмэл', 'a few friends, a little money'],
    structure: [
      { form: 'Countable', pos: 'many books / a few books', neg: '—', q: '—' },
      { form: 'Uncountable', pos: 'much time / a little time', neg: '—', q: '—' },
    ],
    note: 'much ихэвчлэн сөрөг/асуух өгүүлбэрт, батлахад a lot of илүү түгээмэл (I have a lot of time).',
    examples: { Батлах: ex([['I have a few friends here.', 'Надад энд цөөн найз бий.'], ["There isn't much time.", 'Хугацаа их үлдээгүй байна.'], ['I have a lot of books.', 'Надад олон ном бий.']]) },
    mistakes: [['I have much friends.', 'I have many friends.', 'countable-д many.'], ['a few water', 'a little water', 'uncountable-д a little.']],
    practice: [{ type: 'fill', q: 'There are ___ people in the park today.', options: ['much', 'many', 'a little'], answer: 1 }],
    quiz: [
      { q: 'I have ___ money left — just enough for lunch.', options: ['many', 'a little', 'a few'], answer: 1 },
      { q: 'How ___ apples do you want?', options: ['much', 'many', 'a little'], answer: 1 },
    ],
    related: ['countable-uncountable'],
  },
  {
    id: 'question-tags', book: 'essential-grammar-in-use', level: 'A2', title: 'Question Tags', icon: 'Qt', time: '12 мин',
    desc: "Баталгаажуулах жижиг асуулт (..., isn't it?).",
    definition: 'Question tag нь өгүүлбэрийн төгсгөлд орж, батлахыг эсвэл зөвшөөрлийг хүсдэг жижиг асуулт (батлах өгүүлбэрт сөрөг tag, сөрөг өгүүлбэрт батлах tag).',
    useCases: ["Батлах өгүүлбэр → сөрөг tag (You are tired, aren't you?)", "Сөрөг өгүүлбэр → батлах tag (You aren't tired, are you?)"],
    structure: [
      { form: 'Батлах + сөрөг tag', pos: "She is nice, isn't she?", neg: '—', q: '—' },
      { form: 'Сөрөг + батлах tag', pos: "He doesn't smoke, does he?", neg: '—', q: '—' },
    ],
    note: 'Tag нь өгүүлбэрийн туслах үйл үгтэй тохирно (be→be, do→do, have→have, can→can гэх мэт). Үндсэн үйл үгтэй бол do/does/did ашиглана.',
    examples: { Батлах: ex([["It's cold today, isn't it?", 'Өнөөдөр хүйтэн байна, тийм үү?'], ["You like coffee, don't you?", 'Чи кофенд дуртай, тийм үү?'], ["They can swim, can't they?", 'Тэд усанд сэлж чаддаг, тийм үү?']]) },
    mistakes: [['You are tired, are you?', "You are tired, aren't you?", 'Батлахад сөрөг tag хэрэгтэй.'], ['She likes tea, does she not like?', "She likes tea, doesn't she?", 'Товчилсон хэлбэр ашиглана.']],
    practice: [{ type: 'fill', q: 'You speak English, ___ you?', options: ['do', "don't", "aren't"], answer: 1 }],
    quiz: [
      { q: "He isn't coming, ___ he?", options: ['is', "isn't", 'does'], answer: 0 },
      { q: 'They have finished, ___ they?', options: ['have', "haven't", "don't"], answer: 1 },
    ],
    related: ['question-forms'],
  },
  {
    id: 'adjectives-adverbs', book: 'essential-grammar-in-use', level: 'A2', title: 'Adjectives vs Adverbs (good/well)', icon: 'Av', time: '10 мин',
    desc: 'Тэмдэг нэр ба дайвар үгийн ялгаа.',
    definition: 'Adjective (тэмдэг нэр) нь нэр үгийг тодотгоно, adverb (дайвар үг) нь үйл үг/тэмдэг нэрийг тодотгоно. Ихэнх adverb нь adjective + -ly.',
    useCases: ['adjective + нэр үг (a good book)', 'adverb + үйл үг (sing well)', 'good → well (онцгой хэлбэр)'],
    structure: [
      { form: 'Adjective', pos: 'a quick answer', neg: '—', q: '—' },
      { form: 'Adverb', pos: 'answer quickly', neg: '—', q: '—' },
    ],
    note: 'good (adjective) → well (adverb), тусдаа үг. fast, hard, late зэрэг adjective, adverb хоёуланд ижил хэлбэртэй.',
    examples: { Батлах: ex([['She is a good singer.', 'Тэр сайн дуучин.'], ['She sings well.', 'Тэр сайн дуулдаг.'], ['He drives carefully.', 'Тэр болгоомжтой жолоо барьдаг.']]) },
    mistakes: [['She sings good.', 'She sings well.', 'Үйл үгийг adverb тодотгоно.'], ['He drives careful.', 'He drives carefully.', '-ly дуусгавартай adverb хэрэгтэй.']],
    practice: [{ type: 'fill', q: 'He plays football very ___.', options: ['good', 'well', 'goodly'], answer: 1 }],
    quiz: [
      { q: 'This is a ___ problem.', options: ['difficult', 'difficultly', 'difficulty'], answer: 0 },
      { q: 'She speaks English ___.', options: ['fluent', 'fluently', 'fluenty'], answer: 1 },
    ],
    related: ['comparative'],
  },
  {
    id: 'verb-preposition', book: 'essential-grammar-in-use', level: 'A2', title: 'Verb + Preposition (listen to/look at)', icon: 'Vp', time: '10 мин',
    desc: 'Тогтмол предлогтой хамт ирдэг үйл үгс.',
    definition: 'Зарим үйл үг тодорхой предлогтой хамт л зөв утгаараа ашиглагдана: listen to, look at, wait for, depend on гэх мэт.',
    useCases: ['listen to music', 'look at the picture', 'wait for the bus', 'depend on you'],
    structure: [
      { form: 'listen to', pos: 'I listen to music.', neg: '—', q: '—' },
      { form: 'wait for', pos: 'She is waiting for the bus.', neg: '—', q: '—' },
    ],
    note: 'Эдгээр хослолыг цээжлэх нь хамгийн сайн арга — англи хэлэнд логикоор тааж болдоггүй.',
    examples: { Батлах: ex([['I listen to the radio every morning.', 'Би өглөө бүр радио сонсдог.'], ['Look at that beautiful sunset!', 'Тэр үзэсгэлэнтэй нар жаргалтыг хараарай!'], ['It depends on the weather.', 'Энэ цаг агаараас хамаарна.']]) },
    mistakes: [['listen music', 'listen to music', 'listen-ийн дараа to заавал орно.'], ['wait the bus', 'wait for the bus', 'wait-ийн дараа for.']],
    practice: [{ type: 'fill', q: 'She is listening ___ music.', options: ['at', 'to', 'for'], answer: 1 }],
    quiz: [
      { q: 'I am waiting ___ my friend.', options: ['for', 'to', 'at'], answer: 0 },
      { q: 'Look ___ this photo!', options: ['to', 'for', 'at'], answer: 2 },
    ],
    related: ['prepositions-place'],
  },

  // ── B1 (Essential Grammar in Use) ──
  {
    id: 'present-perfect-continuous', book: 'essential-grammar-in-use', level: 'B1', title: 'Present Perfect Continuous', icon: 'Pfc', time: '16 мин',
    desc: 'Өнгөрснөөс одоог хүртэл үргэлжилсэн, одоо ч болж байгаа үйлдэл.',
    definition: 'have/has been + V-ing нь өнгөрснөөс эхэлж одоог хүртэл үргэлжилж буй (эсвэл сая дуусаад үр дүн нь мэдрэгдэж буй) үйлдлийг илэрхийлнэ.',
    useCases: ['Хэр удаан үргэлжилснийг онцлох (for/since)', 'Саяхан дууссан үйл ажиллагааны үр дүн одоо мэдрэгдэх'],
    structure: [
      { form: 'I / You / We / They', pos: 'have been working.', neg: "haven't been working.", q: 'Have you been working?' },
      { form: 'He / She / It', pos: 'has been working.', neg: "hasn't been working.", q: 'Has he been working?' },
    ],
    note: 'Present Perfect Simple (үр дүн, хэдэн удаа) vs Continuous (үргэлжлэл, хугацаа) — "I have read 3 books" (тоо) vs "I have been reading for 2 hours" (үргэлжлэл).',
    examples: {
      Батлах: ex([['I have been studying English for 3 years.', 'Би 3 жилийн турш англи хэл сурч байна.'], ['She has been waiting for an hour.', 'Тэр нэг цагийн турш хүлээж байна.']]),
      Сөрөг: ex([["We haven't been sleeping well.", 'Бид сайн унтаагүй байна.']]),
      Асуух: ex([['How long have you been living here?', 'Чи энд хэр удаан амьдарч байна вэ?']]),
    },
    mistakes: [['I am studying English since 2020.', 'I have been studying English since 2020.', 'since-тэй Present Perfect Continuous.']],
    practice: [{ type: 'fill', q: 'It ___ raining since morning.', options: ['is', 'has been', 'was'], answer: 1 }],
    quiz: [
      { q: 'She ___ working here since 2019.', options: ['is', 'has been', 'was'], answer: 1 },
      { q: 'How long ___ you been waiting?', options: ['have', 'are', 'did'], answer: 0 },
    ],
    related: ['present-perfect', 'past-continuous'],
  },
  {
    id: 'past-perfect', book: 'essential-grammar-in-use', level: 'B1', title: 'Past Perfect (had done)', icon: 'Pp2', time: '15 мин',
    desc: 'Өнгөрсний өнгөрсөн — өнгөрсний хоёр үйл явдлын дараалал.',
    definition: 'had + V3 нь өнгөрсний өөр нэг үйл явдлаас ӨМНӨ болсон үйлдлийг илэрхийлнэ.',
    useCases: ['Өнгөрсний хоёр үйлдлийн дарааллыг тодруулах', 'Түүх ярихад "аль хэдийн" гэдгийг онцлох'],
    structure: [{ form: 'Бүх бие', pos: 'had finished.', neg: "had not (hadn't) finished.", q: 'Had you finished?' }],
    note: 'Past Perfect ашигласнаар аль үйлдэл эхэлж болсныг тодорхой болгоно: "When I arrived, the film had already started" (кино намайг ирэхээс өмнө эхэлсэн).',
    examples: { Батлах: ex([['When I arrived, she had already left.', 'Намайг ирэхэд тэр аль хэдийн явчихсан байсан.'], ['I had never seen snow before I visited Mongolia.', 'Монголд очихоосоо өмнө би цас хэзээ ч харж байгаагүй.']]) },
    mistakes: [['When I arrived, she already left.', 'When I arrived, she had already left.', 'Эхэлсэн үйлдэлд Past Perfect хэрэгтэй.']],
    practice: [{ type: 'fill', q: 'By the time we got there, the movie ___.', options: ['started', 'had started', 'starts'], answer: 1 }],
    quiz: [
      { q: 'She ___ finished her homework before dinner.', options: ['has', 'had', 'have'], answer: 1 },
      { q: 'I realized I ___ forgotten my keys.', options: ['have', 'had', 'was'], answer: 1 },
    ],
    related: ['past-simple', 'present-perfect'],
  },
  {
    id: 'reported-speech', book: 'essential-grammar-in-use', level: 'B1', title: 'Reported Speech', icon: 'Rs', time: '16 мин',
    desc: 'Хэн нэгний хэлсэн үгийг дамжуулан ярих.',
    definition: 'Reported speech-д direct speech-ийн цагийг нэг шат ард (present→past, past→past perfect гэх мэт) шилжүүлдэг.',
    useCases: ['Хэн нэгний хэлсэн зүйлийг дамжуулах', 'said/told ашиглах'],
    structure: [
      { form: 'Present Simple → Past Simple', pos: '"I work here." → He said he worked there.', neg: '—', q: '—' },
      { form: 'Present Perfect → Past Perfect', pos: '"I have finished." → She said she had finished.', neg: '—', q: '—' },
    ],
    note: 'said + (that), told + хүн + (that). Цаг заасан үг ч мөн өөрчлөгдөнө: now→then, today→that day, tomorrow→the next day.',
    examples: { Батлах: ex([['"I am tired," she said. → She said she was tired.', '"Би ядарсан байна" гэж тэр хэлсэн → Тэр ядарсан гэж хэлсэн.'], ['"I will call you," he said. → He said he would call me.', '"Би чамд залгана" гэж тэр хэлсэн.']]) },
    mistakes: [['She said she is tired.', 'She said she was tired.', 'Цаг нэг шат ард шилжинэ.']],
    practice: [{ type: 'fill', q: '"I am busy," she said. → She said she ___ busy.', options: ['is', 'was', 'has been'], answer: 1 }],
    quiz: [
      { q: '"I will help you," he said. → He said he ___ help me.', options: ['will', 'would', 'can'], answer: 1 },
      { q: '"I have lost my keys," she said. → She said she ___ her keys.', options: ['lost', 'has lost', 'had lost'], answer: 2 },
    ],
    related: ['past-simple', 'present-perfect'],
  },
  {
    id: 'phrasal-verbs', book: 'essential-grammar-in-use', level: 'B1', title: 'Phrasal Verbs (get up/turn on)', icon: 'Ph', time: '12 мин',
    desc: 'Үйл үг + жижиг үг хослол, шинэ утгатай болно.',
    definition: 'Phrasal verb нь үйл үг + дайвар/предлог (up, on, off, out гэх мэт) нийлж, эх утгаас өөр шинэ утга үүсгэдэг хослол.',
    useCases: ['Өдөр тутмын ярианд түгээмэл', 'Заримыг задлаж (separable), заримыг задлахгүй (inseparable) хэрэглэнэ'],
    structure: [
      { form: 'Separable', pos: 'turn on the light / turn the light on / turn it on', neg: '—', q: '—' },
      { form: 'Inseparable', pos: 'look after the baby (look the baby after биш)', neg: '—', q: '—' },
    ],
    note: 'Товчилсон төлөөний үг (it, them) заавал үйл үг ба дайвар үгийн ХООРОНД орно: turn it on (turn on it биш).',
    examples: { Батлах: ex([['I get up at 7 every day.', 'Би өдөр бүр 7 цагт босдог.'], ['Can you turn off the TV?', 'Чи зурагтыг унтраагаад өгөх үү?'], ['She looks after her little brother.', 'Тэр дүүгээ асардаг.']]) },
    mistakes: [['turn on it', 'turn it on', 'Төлөөний үг дунд орно.'], ['look after of the baby', 'look after the baby', 'after дараа of ордоггүй.']],
    practice: [{ type: 'fill', q: "Please turn ___ the music, it's too loud.", options: ['down', 'at', 'in'], answer: 0 }],
    quiz: [
      { q: 'I need to give ___ smoking.', options: ['up', 'on', 'out'], answer: 0 },
      { q: 'Can you pick ___ some milk on your way home?', options: ['up', 'on', 'off'], answer: 0 },
    ],
    related: ['verb-preposition'],
  },
  {
    id: 'too-enough', book: 'essential-grammar-in-use', level: 'B1', title: 'Too / Enough', icon: 'Te', time: '10 мин',
    desc: 'Хэт их/хангалттай гэдгийг илэрхийлэх.',
    definition: 'too + тэмдэг нэр (хэтэрхий, сөрөг утгатай), тэмдэг нэр + enough (хангалттай).',
    useCases: ['too + adjective — сөрөг, хэт их', 'adjective + enough — хангалттай'],
    structure: [
      { form: 'too', pos: 'too expensive', neg: '—', q: '—' },
      { form: 'enough', pos: 'cheap enough', neg: '—', q: '—' },
    ],
    note: 'too нь adjective-ийн ӨМНӨ, enough нь adjective-ийн ДАРАА орно. too нь сөрөг санааг илэрхийлдэг (too big = хэтэрхий том, болохгүй).',
    examples: { Батлах: ex([['This coffee is too hot.', 'Энэ кофе хэтэрхий халуун байна.'], ["She isn't old enough to drive.", 'Тэр жолоо барихад хангалттай насанд хүрээгүй байна.'], ['Is the room big enough?', 'Өрөө хангалттай том уу?']]) },
    mistakes: [['This is enough big.', 'This is big enough.', 'enough adjective-ийн ДАРАА орно.'], ['too much big', 'too big', 'adjective-ийн өмнө зөвхөн too.']],
    practice: [{ type: 'fill', q: 'This bag is ___ heavy to carry.', options: ['too', 'enough', 'so'], answer: 0 }],
    quiz: [
      { q: "He isn't tall ___ to reach the shelf.", options: ['too', 'enough', 'so'], answer: 1 },
      { q: "It's ___ cold to swim today.", options: ['enough', 'too', 'very'], answer: 1 },
    ],
    related: ['comparative', 'adjectives-adverbs'],
  },
];

export default LESSONS;

export function findLesson(id) { return LESSONS.find(l => l.id === id); }
export function lessonsByLevel(level) { return LESSONS.filter(l => l.level === level); }
