// Ой тогтоолтын олон улсын судалгааны загварууд
// Memory Science Knowledge Platform — model library data

export const CATEGORIES = [
  'Мэдээлэл боловсруулах',
  'Олон бүрэлдэхүүнт ой',
  'Ажлын ой',
  'Урт хугацааны ой',
  'Туршилт, хэмжилт',
];

const MODELS = [
  {
    id: 'atkinson-shiffrin',
    title: 'Atkinson–Shiffrin загвар',
    category: 'Мэдээлэл боловсруулах',
    icon: '⚙️',
    authors: 'Richard Atkinson, Richard Shiffrin',
    year: 1968,
    university: 'Stanford University',
    concept: 'Анхаарал, дахин давтах, кодлох, сэргээн санах',
    related: 'Санах ойн багтаамж, хадгалах хугацаа, мэдээлэл дамжуулах урсгал',
    summary: 'Энэхүү загвар нь ойг гурван үндсэн санах ойн системээр тайлбарладаг: мэдрэхүйн ой, богино хугацааны ой (ажлын ой), урт хугацааны ой. Мэдээлэл эдгээр шатуудаар дамжин урсдаг.',
    diagram: 'flow3', // тусгай 3-боксын урсгал
    structure: [
      { color: '#8B5CF6', title: 'Мэдрэхүйн ой (Sensory Memory)', text: 'Орчин тойрноос ирж буй мэдээлэл маш богино хугацаанд хадгалагдана (0.25–2 секунд).', ex: 'Дуу, дүрс, мэдрэмж' },
      { color: '#F59E0B', title: 'Богино хугацааны ой / Ажлын ой (Short-Term Memory)', text: 'Анхаарлын төвд орсон мэдээлэл 15–30 секунд хадгалагдана. Дахин давтах замаар урт хугацааны ой руу шилжинэ.', ex: 'Багтаамж: 7±2 нэгж мэдээлэл' },
      { color: '#10B981', title: 'Урт хугацааны ой (Long-Term Memory)', text: 'Мэдээлэл цаг хугацааны хязгааргүй хадгалагдана. Утга агуулгаар нь кодлогдож хадгалагдана.', ex: 'Үнэн баримт, чадвар, туршлага' },
    ],
    advantages: [
      'Ойн бүтцийг ойлгомжтой гурван шатаар тайлбарласан анхны систем загвар.',
      'Богино ба урт хугацааны ойг тусад нь ялгаж үзсэн нь олон судалгаагаар батлагдсан.',
      'Сурах процессыг загварчлахад суурь болсон.',
    ],
    limitations: [
      'Богино хугацааны ойг хэт энгийн нэгдмэл хэсэг гэж үзсэн (Baddeley үүнийг сайжруулсан).',
      'Дахин давтахаас гадна гүн боловсруулалт ойд нөлөөлдгийг тооцоогүй.',
      'Урт хугацааны ойн дотоод бүтцийг задлаагүй.',
    ],
    applications: [
      'Spaced repetition (зайтай давталт) системийн онолын суурь.',
      'Flashcard сургалтын аргачлал.',
      'Анхаарал төвлөрүүлэх дасгалууд.',
    ],
    references: [
      'Atkinson, R. C., & Shiffrin, R. M. (1968). Human memory: A proposed system and its control processes.',
      'Psychology of Learning and Motivation, 2, 89–195.',
    ],
  },
  {
    id: 'baddeley-working',
    title: 'Baddeley-ийн Ажлын ойн загвар',
    category: 'Ажлын ой',
    icon: '🧩',
    authors: 'Alan Baddeley, Graham Hitch',
    year: 1974,
    university: 'University of York',
    concept: 'Төв гүйцэтгэгч, фонологийн гогцоо, харааны зураглал',
    related: 'Богино хугацааны ой, анхаарал, мэдээлэл боловсруулалт',
    summary: 'Ажлын ой нь зүгээр нэг агуулах биш, харин хэд хэдэн дэд системээс бүрдэх идэвхтэй боловсруулах систем гэдгийг харуулсан. Богино хугацааны ойн нэгдмэл загварыг орлуулсан.',
    diagram: 'components',
    structure: [
      { color: '#7C3AED', title: 'Төв гүйцэтгэгч (Central Executive)', text: 'Анхаарлыг хуваарилж, дэд системүүдийг удирддаг хяналтын төв.', ex: 'Шийдвэр гаргах, анхаарал' },
      { color: '#3B82F6', title: 'Фонологийн гогцоо (Phonological Loop)', text: 'Дуу авиа, ярианы мэдээллийг түр хадгалж дотроо давтдаг.', ex: 'Утасны дугаар цээжлэх' },
      { color: '#EC4899', title: 'Харааны зураглал (Visuospatial Sketchpad)', text: 'Харааны болон орон зайн мэдээллийг боловсруулдаг.', ex: 'Замын зураг төсөөлөх' },
      { color: '#10B981', title: 'Эпизод буфер (Episodic Buffer)', text: '2000 онд нэмэгдсэн — өөр өөр эх сурвалжийн мэдээллийг нэгтгэдэг.', ex: 'Дүр зураг бүхэлд нь санах' },
    ],
    advantages: [
      'Богино хугацааны ойн нарийн дотоод бүтцийг тайлбарласан.',
      'Олон туршилтаар (dual-task) батлагдсан.',
      'Хэл сурах, унших чадварыг тайлбарлахад өргөн ашиглагддаг.',
    ],
    limitations: [
      'Төв гүйцэтгэгчийн яг үүрэг бүрэн тодорхойгүй хэвээр.',
      'Дэд системүүдийн хоорондын харилцаа төвөгтэй.',
    ],
    applications: [
      'Хэл сурахад фонологийн гогцоог ашиглах (чанга давтах).',
      'Харааны санамжийн дасгал (зураг + үг хослуулах = Dual Coding).',
    ],
    references: [
      'Baddeley, A. D., & Hitch, G. (1974). Working memory. Psychology of Learning and Motivation, 8, 47–89.',
    ],
  },
  {
    id: 'levels-of-processing',
    title: 'Levels of Processing (Craik & Lockhart)',
    category: 'Мэдээлэл боловсруулах',
    icon: '🧠',
    authors: 'Fergus Craik, Robert Lockhart',
    year: 1972,
    university: 'University of Toronto',
    concept: 'Гадаргуу боловсруулалт, гүн боловсруулалт, утга агуулга',
    related: 'Кодлох гүн, утгазүйн боловсруулалт, ой бэхжүүлэх',
    summary: 'Мэдээллийг хэр гүн боловсруулснаас ой тогтоолт хамаардаг. Утга агуулгаар (гүн) боловсруулсан мэдээлэл гадаргуугаар (өнгө, дуудлага) боловсруулснаас илүү сайн тогтдог.',
    diagram: 'levels',
    structure: [
      { color: '#94A3B8', title: 'Бүтцийн боловсруулалт (Shallow)', text: 'Үгийн гадаад хэлбэр, том/жижиг үсэг зэргийг л анзаарна. Хамгийн муу тогтоодог.', ex: 'Үг ТОМ үсгээр бичигдсэн үү?' },
      { color: '#F59E0B', title: 'Фонетик боловсруулалт (Phonemic)', text: 'Үгийн дуудлага, авиаг боловсруулна. Дунд зэрэг тогтоодог.', ex: 'Энэ үг "cat"-тай ижил сүүлтэй юу?' },
      { color: '#10B981', title: 'Утгазүйн боловсруулалт (Semantic / Deep)', text: 'Үгийн утга, холбоог боловсруулна. Хамгийн сайн тогтоодог.', ex: 'Энэ үг өгүүлбэрт тохирох уу?' },
    ],
    advantages: [
      'Яагаад зарим зүйл сайн тогтдгийг боловсруулалтын гүнгээр тайлбарласан.',
      'Идэвхтэй сургалтын (active learning) онолын үндэс.',
    ],
    limitations: [
      '"Гүн" гэдгийг тоон утгаар хэмжихэд хүндрэлтэй (тойрог тодорхойлолт).',
      'Боловсруулалтын төрөл бус, хэмжээ ч нөлөөлдөг.',
    ],
    applications: [
      'Үг цээжлэхдээ утга, жишээ өгүүлбэртэй холбож сурах.',
      'Зүгээр давтахаас илүү "яагаад?" гэж асуух элаборатив арга.',
    ],
    references: [
      'Craik, F. I. M., & Lockhart, R. S. (1972). Levels of processing: A framework for memory research.',
    ],
  },
  {
    id: 'multi-store',
    title: 'Multi-store Model',
    category: 'Олон бүрэлдэхүүнт ой',
    icon: '🔗',
    authors: 'Atkinson & Shiffrin (өргөтгөсөн)',
    year: 1968,
    university: 'Stanford University',
    concept: 'Олон тусдаа агуулах, шилжих урсгал',
    related: 'Мэдрэхүй, богино, урт хугацааны ой',
    summary: 'Ой нь хоорондоо холбогдсон олон тусдаа агуулахаас бүрдэнэ. Мэдээлэл нэг агуулахаас нөгөө рүү тодорхой нөхцлөөр шилждэг.',
    diagram: 'flow3',
    structure: [
      { color: '#8B5CF6', title: 'Мэдрэхүйн агуулах', text: 'Бүх мэдрэхүйн орц түр хадгалагдана.', ex: 'Iconic, echoic memory' },
      { color: '#F59E0B', title: 'Богино хугацааны агуулах', text: 'Анхаарал хандуулсан мэдээлэл орно.', ex: '7±2 нэгж' },
      { color: '#10B981', title: 'Урт хугацааны агуулах', text: 'Давтагдсан мэдээлэл байнга хадгалагдана.', ex: 'Хязгааргүй багтаамж' },
    ],
    advantages: ['Ойн урсгалыг загварчилсан анхны бүтэц.', 'Туршилтаар хялбар шалгагддаг.'],
    limitations: ['Хэт шугаман, нэг чигийн урсгал гэж үзсэн.', 'Боловсруулалтын гүнг тооцоогүй.'],
    applications: ['Сургалтын дараалал төлөвлөх.', 'Давталтын хуваарь зохиох.'],
    references: ['Atkinson & Shiffrin (1968). Human memory: A proposed system.'],
  },
  {
    id: 'tulving',
    title: 'Tulving-ийн ойн системийн загвар',
    category: 'Урт хугацааны ой',
    icon: '🌳',
    authors: 'Endel Tulving',
    year: 1972,
    university: 'University of Toronto',
    concept: 'Эпизод ой, утгазүйн ой, процедур ой',
    related: 'Урт хугацааны ой, тунхаглах/тунхаглахгүй ой',
    summary: 'Урт хугацааны ойг агуулгаар нь хэд хэдэн системд хувааж үзсэн: эпизод (үйл явдал), утгазүйн (баримт), процедур (чадвар).',
    diagram: 'tree',
    structure: [
      { color: '#10B981', title: 'Эпизод ой (Episodic)', text: 'Хувийн туршлага, тодорхой үйл явдлуудыг цаг хугацаатай нь хадгална.', ex: 'Өчигдрийн оройн хоол' },
      { color: '#3B82F6', title: 'Утгазүйн ой (Semantic)', text: 'Ерөнхий мэдлэг, баримт, ойлголтуудыг хадгална.', ex: 'Улаанбаатар бол нийслэл' },
      { color: '#F59E0B', title: 'Процедур ой (Procedural)', text: 'Чадвар, дадал — хэрхэн хийхийг мэдэх ой.', ex: 'Дугуй унах, бичих' },
    ],
    advantages: ['Урт хугацааны ойн төрлүүдийг ялгаж тайлбарласан.', 'Тархины өөр өөр хэсэгтэй холбогддог нь батлагдсан.'],
    limitations: ['Системүүдийн хил хязгаар үргэлж тодорхой биш.'],
    applications: ['Хэлний дүрмийг (procedural) ба үгсийг (semantic) өөр аргаар сургах.'],
    references: ['Tulving, E. (1972). Episodic and semantic memory.'],
  },
  {
    id: 'transfer-appropriate',
    title: 'Transfer Appropriate Processing (Morris)',
    category: 'Мэдээлэл боловсруулах',
    icon: '🔄',
    authors: 'C. D. Morris, J. Bransford, J. Franks',
    year: 1977,
    university: 'Vanderbilt University',
    concept: 'Кодлох ба сэргээх нөхцлийн тохирол',
    related: 'Context-dependent memory, retrieval',
    summary: 'Сурах үеийн боловсруулалт болон шалгах үеийн боловсруулалт хоорондоо тохирч байвал ой илүү сайн ажилладаг.',
    diagram: 'generic',
    structure: [
      { color: '#7C3AED', title: 'Кодлох нөхцөл', text: 'Мэдээллийг хэрхэн боловсруулж сурсан.', ex: 'Дуудлагаар эсвэл утгаар' },
      { color: '#10B981', title: 'Сэргээх нөхцөл', text: 'Шалгалт нь сурсан аргатай тохирвол үр дүн сайн.', ex: 'Сурсан шигээ шалгагдах' },
    ],
    advantages: ['Levels of Processing-ийг боловсронгуй болгосон.', 'Шалгалтын хэлбэрийн ач холбогдлыг харуулсан.'],
    limitations: ['Бүх нөхцөлд хэмжихэд төвөгтэй.'],
    applications: ['Сурах болон шалгах хэлбэрийг ижил болгох (жишээ: ярьж сурвал ярьж шалгуулах).'],
    references: ['Morris, C. D. et al. (1977). Levels of processing versus transfer appropriate processing.'],
  },
  {
    id: 'memory-hierarchy',
    title: 'Memory Hierarchy',
    category: 'Олон бүрэлдэхүүнт ой',
    icon: '🔺',
    authors: 'Танин мэдэхүйн сэтгэл судлал',
    year: 1970,
    university: '—',
    concept: 'Шаталсан бүтэц, багтаамж ба хугацаа',
    related: 'Мэдрэхүй → богино → урт хугацаа',
    summary: 'Ойг багтаамж ба хадгалах хугацаагаар нь шаталсан пирамид хэлбэрээр дүрсэлдэг. Доод шат нь хурдан боловч багтаамж бага.',
    diagram: 'pyramid',
    structure: [
      { color: '#EF4444', title: 'Мэдрэхүйн ой', text: 'Хамгийн хурдан, хамгийн богино.', ex: '< 2 секунд' },
      { color: '#F59E0B', title: 'Богино хугацааны ой', text: 'Хязгаарлагдмал багтаамж.', ex: '7±2, ~30 сек' },
      { color: '#10B981', title: 'Урт хугацааны ой', text: 'Бараг хязгааргүй багтаамж, удаан хадгална.', ex: 'Жилээр' },
    ],
    advantages: ['Ойн шатлалыг ойлгомжтой харуулдаг.'],
    limitations: ['Хэт хялбаршуулсан төсөөлөл.'],
    applications: ['Сургалтын ачааллыг (cognitive load) тооцоолох.'],
    references: ['Cognitive psychology textbooks.'],
  },
  {
    id: 'context-dependent',
    title: 'Context-Dependent Memory',
    category: 'Мэдээлэл боловсруулах',
    icon: '🧷',
    authors: 'Godden & Baddeley',
    year: 1975,
    university: 'University of Stirling',
    concept: 'Орчны түлхүүр, сэргээх дохио',
    related: 'Encoding specificity, retrieval cue',
    summary: 'Сурсан орчин болон сэргээх орчин ижил байвал ой илүү сайн сэргэдэг. Орчин нь сэргээх дохио болдог.',
    diagram: 'generic',
    structure: [
      { color: '#3B82F6', title: 'Орчны кодлолт', text: 'Сурах үеийн орчин мэдээлэлтэй хамт хадгалагдана.', ex: 'Газар, дуу, үнэр' },
      { color: '#10B981', title: 'Орчны сэргээлт', text: 'Ижил орчинд орвол сэргээх амар.', ex: 'Сурсан өрөөндөө шалгуулах' },
    ],
    advantages: ['Орчны нөлөөг туршилтаар (шумбагчдын туршилт) баталсан.'],
    limitations: ['Бодит амьдралд нөлөө дунд зэрэг.'],
    applications: ['Олон янзын орчинд давтах нь нэг орчноос илүү уян хатан ой бий болгодог.'],
    references: ['Godden, D. R., & Baddeley, A. D. (1975). Context-dependent memory in two natural environments.'],
  },
  {
    id: 'ebbinghaus',
    title: 'Ebbinghaus-ийн Мартах муруй',
    category: 'Туршилт, хэмжилт',
    icon: '📉',
    authors: 'Hermann Ebbinghaus',
    // Нийтийн эзэмшлийн (public domain) жинхэнэ зураг — Wikimedia Commons,
    // "life+70" дүрмээр PD (1850–1909). Бусад загварын судлаачид сүүлийн
    // үеийн/амьд хүмүүс тул зурган avatar ашигладаг (memory/page.js).
    photo: { src: '/scientists/ebbinghaus.jpg', credit: 'Wikimedia Commons — Public domain' },
    year: 1885,
    university: 'University of Berlin',
    concept: 'Мартах хурд, давталтын ач холбогдол',
    related: 'Spacing effect, retention',
    summary: 'Хүн шинэ мэдээллийг хугацаа өнгөрөх тусам экспоненциалаар мартдаг. Гэвч давтах бүрт мартах хурд удааширдаг.',
    diagram: 'curve',
    structure: [
      { color: '#EF4444', title: 'Хурдан уналт', text: 'Эхний цаг, өдөрт ихэнх мэдээлэл мартагдана.', ex: '20 минутад ~42%' },
      { color: '#10B981', title: 'Давталтын нөлөө', text: 'Тогтсон зайтайгаар давтвал муруй тэгшрэнэ.', ex: 'Spaced repetition' },
    ],
    advantages: ['Ойг анх удаа тоон туршилтаар хэмжсэн.', 'Spaced repetition-ийн шинжлэх ухааны үндэс.'],
    limitations: ['Утгагүй үет дээр (nonsense syllables) суурилсан.'],
    applications: ['VOCA-ийн давталтын хуваарь яг энэ муруйд тулгуурладаг.'],
    references: ['Ebbinghaus, H. (1885). Über das Gedächtnis (Memory: A Contribution to Experimental Psychology).'],
  },
  {
    id: 'spacing-effect',
    title: 'Spacing Effect (Зайтай давталт)',
    category: 'Туршилт, хэмжилт',
    icon: '📐',
    authors: 'Cepeda, Pashler нар',
    year: 2006,
    university: 'UC San Diego',
    concept: 'Давталтын хуваарилалт, интервал',
    related: 'Ebbinghaus, retrieval practice',
    summary: 'Нэг дор олон удаа давтахаас (massed) тодорхой зайтайгаар тараан давтах (spaced) нь хол удаан тогтоодог.',
    diagram: 'generic',
    structure: [
      { color: '#EF4444', title: 'Шахсан давталт (Massed)', text: 'Нэг өдөр олон удаа — богино хугацаанд сайн, удаан хугацаанд муу.', ex: 'Шөнөжин чихэх' },
      { color: '#10B981', title: 'Зайтай давталт (Spaced)', text: 'Хэдэн өдрийн зайтай — удаан тогтоодог.', ex: '1 → 3 → 7 → 14 хоног' },
    ],
    advantages: ['Олон зуун туршилтаар баталгаажсан.', 'Хамгийн найдвартай сурах арга.'],
    limitations: ['Оновчтой интервал хүн бүрт өөр.'],
    applications: ['SRS алгоритм (SM-2, Anki, VOCA) яг үүн дээр суурилдаг.'],
    references: ['Cepeda, N. J. et al. (2006). Distributed practice in verbal recall tasks.'],
  },
  {
    id: 'retrieval-practice',
    title: 'Retrieval Practice (Testing Effect)',
    category: 'Туршилт, хэмжилт',
    icon: '🎯',
    authors: 'Roediger & Karpicke',
    year: 2006,
    university: 'Washington University',
    concept: 'Идэвхтэй сэргээлт, өөрийгөө шалгах',
    related: 'Active recall, testing effect',
    summary: 'Мэдээллийг дахин уншихаас илүү санах гэж оролдох (өөрийгөө шалгах) нь ойг хүчтэй бэхжүүлдэг.',
    diagram: 'generic',
    structure: [
      { color: '#94A3B8', title: 'Дахин унших (Passive)', text: 'Танил мэдрэмж төрүүлдэг ч ой сул бэхждэг.', ex: 'Тэмдэглэл дахин харах' },
      { color: '#10B981', title: 'Идэвхтэй сэргээх (Active Recall)', text: 'Санах гэж хичээх нь мэдрэлийн холбоог бэхжүүлдэг.', ex: 'Flashcard, асуултад хариулах' },
    ],
    advantages: ['Унших аргаас 50%+ илүү үр дүнтэй.', 'Урт хугацааны тогтоолтыг эрс нэмэгдүүлдэг.'],
    limitations: ['Хүчтэй боловч хэрэглэгчид эхэндээ хэцүү санагддаг.'],
    applications: ['VOCA-ийн flashcard ба тоглоомууд бүгд active recall дээр суурилдаг.'],
    references: ['Roediger, H. L., & Karpicke, J. D. (2006). Test-enhanced learning.'],
  },
  {
    id: 'dual-coding',
    title: 'Dual Coding Theory',
    category: 'Олон бүрэлдэхүүнт ой',
    icon: '🎨',
    authors: 'Allan Paivio',
    year: 1971,
    university: 'University of Western Ontario',
    concept: 'Үг ба дүрсний давхар кодлолт',
    related: 'Visuospatial, verbal memory',
    summary: 'Мэдээллийг үг (verbal) ба дүрс (visual) гэсэн хоёр сувгаар зэрэг кодловол илүү сайн тогтдог. Хоёр код хоорондоо нэмэлт дохио болно.',
    diagram: 'generic',
    structure: [
      { color: '#3B82F6', title: 'Үгийн код (Verbal)', text: 'Хэл, үг хэллэгээр мэдээлэл кодлогдоно.', ex: 'Үгийн тодорхойлолт' },
      { color: '#EC4899', title: 'Дүрсний код (Visual)', text: 'Зураг, дүрслэлээр кодлогдоно.', ex: 'Ханзны зураглал' },
    ],
    advantages: ['Зураг + үг хослуулсан сургалт хамгийн үр дүнтэй.'],
    limitations: ['Бүх ойлголтыг дүрслэх боломжгүй.'],
    applications: ['Ханз тэмдэгтийг зураг + дуудлага + утгатай холбож сурах.'],
    references: ['Paivio, A. (1971). Imagery and verbal processes.'],
  },
];

export default MODELS;

// Холбоотой судалгаа (recommendation) — энгийн дүрэмд суурилсан
export const RELATED = {
  'spacing-effect': ['retrieval-practice', 'ebbinghaus', 'dual-coding'],
  'retrieval-practice': ['spacing-effect', 'levels-of-processing', 'ebbinghaus'],
  'ebbinghaus': ['spacing-effect', 'retrieval-practice'],
  'atkinson-shiffrin': ['multi-store', 'baddeley-working', 'memory-hierarchy'],
  'baddeley-working': ['atkinson-shiffrin', 'dual-coding'],
  'levels-of-processing': ['transfer-appropriate', 'retrieval-practice'],
  'tulving': ['atkinson-shiffrin', 'context-dependent'],
  'multi-store': ['atkinson-shiffrin', 'memory-hierarchy', 'baddeley-working'],
  'transfer-appropriate': ['levels-of-processing', 'context-dependent'],
  'memory-hierarchy': ['atkinson-shiffrin', 'multi-store'],
  'context-dependent': ['transfer-appropriate', 'baddeley-working'],
  'dual-coding': ['baddeley-working', 'spacing-effect'],
};
