export const C = {
  bg:          '#FFFFFF',
  bgAlt:       '#F7F7F7',
  border:      '#E5E5E5',
  green:       '#58CC02',
  greenDark:   '#58A700',
  greenLight:  '#D7FFB8',
  greenBg:     '#EDFFD7',
  gold:        '#FF9600',
  goldDark:    '#CC7800',
  goldLight:   '#FFF0C0',
  blue:        '#1CB0F6',
  blueDark:    '#0099D4',
  blueLight:   '#DFF4FF',
  red:         '#FF4B4B',
  redDark:     '#EA2B2B',
  redLight:    '#FFE0E0',
  purple:      '#CE82FF',
  purpleDark:  '#A560E8',
  text:        '#3C3C3C',
  textMuted:   '#AFAFAF',
};
